Export CellCoords and CellRange classes
handsontable/handsontable pull request #10120
Opened 2022-11-23 08:20 UTC by budnix

### Context

The PR exports the` CellCoords` and `CellRange` classes and their types to the public. The new modules are available under the named import:
```js
import Handsontable, { CellCoords, CellRange } from '/handsontable';
// or modularized version
import Handsontable, { CellCoords, CellRange } from '/handsontable/base';
```
The classes are available in the Handsontable namespace as well:
```js
const cellCoords = new Handsontable.CellCoords(1, 2);
const cellRange = new Handsontable.CellRange(cellCoords, cellCoords, cellCoords);
```

### How has this been tested?

I covered the changes with new typing tests.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes #9755 

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2022-11-23 21:55 UTC, kirszenbaum requested changes
@budnix – I'm adding my propositions in #10123. I took the occasion to clean up the descriptions of all public methods of `CellCords` and `CellRange`.

2022-11-24 08:23 UTC, kirszenbaum approved these changes

2022-11-29 17:05 UTC, budnix commented
🏓 @jansiegel

2022-12-01 11:53 UTC, jansiegel approved these changes
Looks alright 👍

2022-12-01 11:55 UTC, merged