Implement redirect mechanism to the pages between different Docs versions
handsontable/handsontable pull request #10163
Opened 2022-12-13 12:38 UTC by budnix

### Context

WIP

_[skip changelog]_

### How has this been tested?

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/9

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

2022-12-15 11:06 UTC, budnix commented
@kirszenbaum, I've added you as a secondary reviewer. The PR adds a new feature to the Docs that requires changes in creating new pages. I thought you'd be interested. Especially about reviewing the [README-EDITING.md](https://github.com/handsontable/handsontable/pull/10163/files#diff-d7e656edc6b6824b076b84acdec3ba38907deeac521cd5e691f26b1914773d41R21) file

2022-12-15 15:01 UTC, kirszenbaum requested changes

2022-12-15 15:01 UTC, kirszenbaum commented on docs/README-EDITING.md
> +| `id`             | The page's uniq id.                                  | The value is required and is used for the Docs page redirection between different Docs versions (https://github.com/handson
```suggestion
| `id`             | The page's unique ID.                                  | Required. Used for redirecting between different versions (e.g., 12.1 to 11.0) of the same documentation page (https://github.com/handsontable/handsontable/pull/10163). Don't change the IDs of existing pages. To add an ID for a new page, generate 8 random alphanumeric characters (https://www.random.org/strings/?num=20&len=8&digits=on&loweralpha=on&unique=on&format=html&rnd=new). |
```

2022-12-16 12:53 UTC, jansiegel approved these changes
Test it the same way you described, and it seems to work all right 👍

2022-12-16 13:04 UTC, merged