Docs: Update mobile support info
handsontable/handsontable pull request #10221
Opened 2023-01-27 12:53 UTC by kirszenbaum

This PR:
- Updates the [Supported browsers](https://handsontable.com/docs/react-data-grid/supported-browsers/) page to reflect the actual state of testing (as reported by @aninde in [#951](https://github.com/handsontable/dev-handsontable/issues/951))

[skip changelog]

2023-02-03 09:38 UTC, aninde requested changes

2023-02-03 09:38 UTC, aninde commented on docs/content/guides/technical-specification/mobile-support.md
> +| [Column freezing](@/guides/columns/column-moving.md)                       |     &cross;      |   &cross;    |   &cross;    |
Wrong link. It can be marked as "checked" . I test it on Android using the context menu and during testing documentation on iOS.

2023-02-03 09:38 UTC, aninde commented on docs/content/guides/technical-specification/mobile-support.md
> +| [Comments](@/guides/cell-features/comments.md)                             |     &cross;      |   &cross;    |   &cross;    |
This can be marked as "checked" . I test it on Android using the context menu and during testing documentation on iOS.

2023-02-03 09:38 UTC, aninde commented on docs/content/guides/technical-specification/mobile-support.md
> +| [Export to CSV](@/guides/accessories-and-menus/export-to-csv.md)           |     &cross;      |   &cross;    |   &cross;    |
It can be marked as "checked". I test it during checking documentation.

2023-02-03 09:38 UTC, aninde commented on docs/content/guides/technical-specification/mobile-support.md
> +| [Layout direction](@/guides/internationalization/layout-direction.md)      |     &cross;      |   &cross;    |   &cross;    |
It can be marked as "checked"  also, I forgot to mention it. I test scrolling with enabled 'rtl' direction on mobile.

2023-02-03 09:38 UTC, aninde commented on docs/content/guides/technical-specification/supported-browsers.md
> +| Windows | macOS   |
The updated text offers a concise summary of the browsers we support based on the tests we conduct.

2023-02-03 11:46 UTC, AMBudnik submitted a review, later dismissed
I would replace the `To use Handsontable's UI on a mobile device:` with something like `Here's how to use Handsontable on a mobile device because now the structure of the sentence indicates that you'd present steps to follow.

At `To select a range of cells, drag the selection handles that display only on mobile:` we have another colon that does not seem to be necessary.

I'm not sure if I would put functionalities that got `x` in all the columns. Cause then each time we add some functionality, we need to add it to the table, regardless if it works on mobile. 

Besides that, I do not see anything that should be changed, and I have to admit that I like the structure of this guide.

2023-02-06 13:07 UTC, kirszenbaum commented
@AMBudnik @aninde thanks for the review! @Serrrek89 As I'm removing a few browsers from the list of supported browsers, I think it'd be good if you signed off publishing these changes.

2023-02-07 13:38 UTC, aninde requested changes
It's almost perfect. I think we can still add `Row freezing` to the list with 3 checks.

2023-02-07 14:02 UTC, aninde approved these changes

2023-02-14 19:27 UTC, Serrrek89 commented
@krzysztofspilka  I'm asking for final approval :)

A client asked us about HOT support on mobile devices. We have decided that the information contained in our documentation is incomplete and not entirely true. Natalia did research and described current support. On this basis, Kuba prepared appropriate changes in the docs. Below is a brief description of the changes:

**Before:**
Supported browsers were divided into Desktop and Mobile. We did not inform in any way what functionalities are supported on mobile and how to use it. In addition, we assured about some mobile tests, which we did not actually run.

**After:**
Supported browsers are now divided into Mac / PC (desktop) and Andoird / iOS (mobile). We dropped "QQ browser" from supported desktop sites. Opera and Firefox for iOS have been deleted on mobile. We clarified that Samsung Internet and Firefox for Android are supported/tested to some extent.
 
 In addition, we have created a new page that contains information on how to use HOT on mobile and what features are supported on mobile. (simple table)

2023-02-14 20:16 UTC, krzysztofspilka commented
I rejected this PR.

2023-02-14 20:16 UTC, closed without merging