[WIP] Epic branch for accessibility
handsontable/handsontable pull request #10242
Opened 2023-02-13 10:42 UTC by budnix

### Context

The PR is an epic branch that contains different things that improve the accessibility of the component. The branch currently contains the following changes:
 * https://github.com/handsontable/handsontable/pull/10237;

### Related issue(s):
1.

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2023-06-29 14:39 UTC, aninde commented
@budnix there is regression on this branch, found by @krzysztofspilka. 

Increasing the selection range by shortcuts does not work for adding different axes, from vertical to horizontal and vice verse. 
Steps to reproduce: 
On demo https://stackblitz.com/edit/js-4w79ps?file=style.css,index.js  build this PR select cell D3 and 
1. press `Cmd + Shift + Arrow down` and hold `Cmd + Shift`
2. Press `Arrow left`

https://github.com/handsontable/handsontable/assets/30186818/2169c78d-00d7-410e-b006-5fa268a89312

V13.0.0 without this issue  for comparision https://stackblitz.com/edit/js-gr18hr?file=style.css,index.js

https://github.com/handsontable/handsontable/assets/30186818/1bb066da-040a-43a9-be84-a33a040c67d1

2023-07-28 09:52 UTC, kirszenbaum requested changes

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10237.json
> +  "title": "Added Ctrl/Cmd+Shift+Space keyboard shortcut that allows selecting all cells.",
```suggestion
  "title": "Added a keyboard shortcut for selecting all cells.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10265.json
> +  "title": "Added support for keyboard navigation in headers.",
```suggestion
  "title": "Added support for keyboard navigation in row and column headers.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10389.json
> +  "title": "Added support for keyboard shortcuts that allows selecting all rows and columns and add 4 new hooks",
```suggestion
  "title": "Added a keyboard shortcut for selecting all rows and columns. Added 4 new hooks.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10404.json
> +  "title": "Added support for collapsing/expanding columns using a keyboard shortcut.",
```suggestion
  "title": "Added a keyboard shortcut for collapsing or expanding columns.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10405.json
> +  "title": "Added support for collapsing/expanding nested rows using a keyboard shortcut.",
```suggestion
  "title": "Added a keyboard shortcut for collapsing or expanding nested rows.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10410.json
> +  "title": "Added support for column sorting using a keyboard shortcut.",
```suggestion
  "title": "Added a keyboard shortcut for rows sorting.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10413.json
> +  "title": "Added support for keyboard shortcuts that allow open column menu.",
```suggestion
  "title": "Added a keyboard shortcut for opening the column menu.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10417.json
> +  "title": "Added support for keyboard shortcut that allows opening the context menu.",
```suggestion
  "title": "Added a keyboard shortcut for opening the context menu.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10419.json
> +  "title": "Added support for new keyboard shortcut that allows scrolling the viewport",
```suggestion
  "title": "Added a new keyboard shortcut for scrolling the viewport.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10420.json
> +  "title": "Added support for keyboard shortcut that allows clearing the filters.",
```suggestion
  "title": "Added a keyboard shortcut for clearing all filters.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10421.json
> +  "title": "Added a keyboard shortcut that allows managing the cell comments.",
```suggestion
  "title": "Added keyboard shortcuts for managing cell comments.",
```

2023-07-28 09:52 UTC, kirszenbaum commented on .changelogs/10430.json
> +  "title": "Added the ability to traverse the grid using TAB key throughout the page and added new `disableTabNavigation` option.",
```suggestion
  "title": "Added the ability to traverse the grid using the <kbd>Tab</kbd> key throughout the page. Also, added a new configuration option: `disableTabNavigation`.",
```

2023-10-24 10:47 UTC, merged