Prevent unneeded HyperFormula config updates.
handsontable/handsontable pull request #10326
Opened 2023-04-12 13:48 UTC by jansiegel

### Context
Unlike Handsontable, HyperFormula resets its undo stack on every config update (not sure if it _should_, cc @adamu-handsontable). 
See the console in this demo: https://jsfiddle.net/js_ziggle/2uLan4cp/

This PR adds an additional condition to the Formula plugin's `updatePlugin` method to ensure that the settings provided to `hot.updateSettings` would indeed modify the HyperFormula config. Otherwise, the HyperFormula config-updating method will not be called.

### How has this been tested?
Tested manually with the case described in handsontable/dev-handsontable#494 + added a test case.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. handsontable/dev-handsontable#494

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2023-04-26 07:24 UTC, wszymanski requested changes
Please add extra check which will show that `updateConfig` is called in some case.

2023-04-26 10:32 UTC, wszymanski approved these changes
Perfect 👌

2023-04-26 10:33 UTC, merged

2023-04-27 14:31 UTC, sequba commented
Related issue in HyperFormula project: https://github.com/handsontable/hyperformula/issues/1251

2023-05-23 11:48 UTC, AMBudnik commented
Demo updated to 12.4.0 (after official release) https://jsfiddle.net/handsoncode/pLj2xfoy/

Log before the changes
![Zrzut ekranu 2023-05-23 o 13 46 35](https://github.com/handsontable/handsontable/assets/10757813/439e36ff-edd7-460c-b11f-5cad30d5dbfa)

Log after the changes
![Zrzut ekranu 2023-05-23 o 13 47 11](https://github.com/handsontable/handsontable/assets/10757813/28e94926-834d-4902-8e15-205b025209be)