Fixed problems with backlight element misalignment and moving element after the last position
handsontable/handsontable pull request #10348
Opened 2023-05-05 09:33 UTC by wszymanski

### Context

As the title says, just a draft for saving progress.

### How has this been tested?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/501
2. https://github.com/handsontable/dev-handsontable/issues/99
3. https://github.com/handsontable/dev-handsontable/issues/97

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] My change requires a change to the documentation.

2023-05-11 09:06 UTC, budnix requested changes
It works great 💪 Just a small typo to correct.

2023-05-11 09:06 UTC, budnix commented on handsontable/src/plugins/manualRowMove/__tests__/manualRowMoveUI.spec.js
> +        spec().$styleDomEleement = $('<style type="text/css"></style>');
```suggestion
        spec().$styleDomElement = $('<style type="text/css"></style>');
```
Typo

2023-05-11 11:00 UTC, budnix approved these changes

2023-05-11 12:05 UTC, budnix requested changes

2023-05-11 12:05 UTC, budnix commented on handsontable/src/plugins/manualRowMove/__tests__/manualRowMoveUI.spec.js
> +        $(spec().$styleDomEleement).appendTo('body');
```suggestion
        $(document.createTextNode(css)).appendTo(spec().$styleDomElement);
        $(spec().$styleDomElement).appendTo('body');
```

2023-05-11 12:07 UTC, budnix requested changes
The same typos to fix but in different lines

2023-05-11 12:35 UTC, budnix approved these changes

2023-05-11 13:08 UTC, merged

2023-05-23 12:53 UTC, AMBudnik commented
Released in Handsontable v12.4.0