Implement new GitHub issue templates
handsontable/handsontable pull request #10378
Opened 2023-05-22 13:31 UTC by adrianszymanski89

### Context

This PR implements new GitHub issue templates for a better user experience.

### How has this been tested?

The templates were developed and tested in a private repository.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/1318

### Affected project(s):
- [X] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [X] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

[skip changelog]

2023-05-23 10:13 UTC, wszymanski submitted a review, later dismissed
Good job 👍

2023-05-23 12:05 UTC, krzysztofspilka requested changes

2023-05-23 12:05 UTC, krzysztofspilka commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: Please provide a screenshot or a short video presenting the issue
Period symbol missing at the end of the sentence.

2023-05-24 11:21 UTC, AMBudnik approved these changes

2023-05-24 19:08 UTC, krzysztofspilka approved these changes
LGTM

2023-05-25 07:11 UTC, merged