A11y examples
handsontable/handsontable pull request #10578
Opened 2023-11-13 10:39 UTC by evanSe

[skip changelog]

### Context
new a11y demos were not consistent with our existing
- kebab case class/id
- make CSS prettier
- replace svg
- add 3 additional links

### How has this been tested?
ran locally

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [X] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2023-11-13 11:30 UTC, jansiegel commented
Not to extend the scope of this PR too much, but maybe it could fix the problems described here: https://github.com/handsontable/dev-handsontable/issues/1514?

2023-11-13 12:05 UTC, budnix requested changes
While playing a demo, I spotted that the date-type editor behaves buggy. I found that there is a missing `dateFormat` option.

https://github.com/handsontable/handsontable/pull/10578/files#diff-3508ddba73419ba9f798353a01e9eadf9b2ecdc8fee6d854f1b5e3208ff16a5cR37-R41

should be
```js
    {
      data: "sellDate",
      type: "date",
      dateFormat: "D.MM.YYYY",
      allowInvalid: false,
    },
```
The changes apply to all frameworks

Another thing is that the progress bar renderers do not fit in the cell always
![Zrzut ekranu 2023-11-13 o 13 01 13](https://github.com/handsontable/handsontable/assets/571316/64040a01-f2a9-4b6a-b0e7-d478a9a07e72)

Enabling or disabling the "Enable cells virtualization" option freezes the browser. The table is not usable. I'd recommend changing the dataset size to ~500 rows or less.

2023-11-14 11:59 UTC, budnix requested changes

2023-11-14 11:59 UTC, budnix commented on examples/next/docs/js/accessibility/main.js
>    nestedRows: true,
```suggestion
```
There is no more nested dataset used.

2023-11-14 11:59 UTC, budnix commented on examples/next/docs/react/accessibility/src/App.tsx
>    nestedRows: true,
```suggestion
```

2023-11-14 12:04 UTC, budnix approved these changes

2023-11-14 14:15 UTC, budnix approved these changes

2023-11-14 14:23 UTC, merged