Revert most of #10540, modify where `aria-selected` gets applied.
handsontable/handsontable pull request #10605
Opened 2023-11-23 12:29 UTC by jansiegel

### Context
This PR makes the following changes:

- Reverts most of #10540 
- Makes the header not get `aria-selected` when a cell/range is selected. They still get `aria-selected` when they're selected with the `navigableHeaders` option.

---
- [x] remove `aria-description` from `TH` root
- [x] remove `aria-label` from `<button class="changeType" />`
> [!NOTE]  
> A added an `aria-label` attribute with a space (' '), because `aria-hidden` seems to be ignored by NVDA. Without the empty `aria-label`, the button still gets read as "downpointing triangle".

- [x] add role-presentation on ` <div class="relative htLeft" role="presentation" />`
- [x] add role="presentation" on `<span class="colHeader columnSorting sortAction" />`
- [x] revert the additional div `<div class="columnSortingIndicator" aria-hidden="true"></div>`, restore `::before / ::after` logic
- [x] aria-hidden="true" on `<button class="changeType" />`
- [x] row headers shouldn't be marked as aria-selected="true" when a cell is selected, refer to https://handsoncode.atlassian.net/wiki/spaces/PROJ/pages/6297275/Accessibility+-+support+for+screen+readers

### How has this been tested?
Tested manually, modified the existing test cases.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. handsontable/dev-handsontable#1576

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2023-11-23 13:48 UTC, budnix commented on handsontable/src/plugins/filters/ui/select.js
> -    }
Is this also reverted?

2023-11-23 14:04 UTC, jansiegel commented on handsontable/src/plugins/filters/ui/select.js
> -    }
Probably shouldn't be 👍

2023-11-23 14:11 UTC, budnix requested changes

2023-11-23 14:11 UTC, budnix commented on handsontable/src/tableView.js
> +
```suggestion

    if (this.settings.ariaTags) {
      setAttribute(div, ...A11Y_PRESENTATION());
      setAttribute(span, ...A11Y_PRESENTATION());
    }

```
I'd be consistent with other places that add tags.

2023-11-23 14:16 UTC, budnix commented on handsontable/src/selection/highlight/types/focus.js
> +    focusedHeaderAttributes: headerAttributes,
```suggestion
    headerAttributes: headerAttributes,
```
I'd rename the property to a more generic one. The `VisualSelection` class represents a variety of selection layers, and there should not be an option that matches the one layer - in this case "focus" layer.

2023-11-23 14:18 UTC, budnix commented on handsontable/src/3rdparty/walkontable/src/selection/manager.js
> +          }
```suggestion
          if (focusedHeaderAttributes) {
            if (!focusedHeaderAttributesMap.has(element)) {
              focusedHeaderAttributesMap.set(element, []);
            }

            if (element.nodeName === 'TH') {
              focusedHeaderAttributesMap.get(element).push(...focusedHeaderAttributes);
            }
          }
```

2023-11-24 10:30 UTC, budnix submitted a review, later dismissed

2023-11-24 10:49 UTC, budnix approved these changes

2023-11-24 10:49 UTC, merged