Update all docs demos to have autowrap
handsontable/handsontable pull request #10677
Opened 2023-12-20 13:04 UTC by evanSe

### Description
Update documentation to present the best accessibility experience out of the box, removal of progress, stars and row header checkbox and set autowrapping to true on all demos.

```
autoWrapRow: true,
autoWrapCol: true,
```

- [ ] remove all progress cell types from demos
- [ ] Remove all star cell types from the demo
- [ ] Remove all row header checkboxes from demo's 
- [x] `autoWrapRow: true` on all demos
- [x] `autoWrapCol: true` on all demos

2023-12-20 13:10 UTC, budnix requested changes

2023-12-20 13:10 UTC, budnix commented on docs/content/guides/cell-functions/cell-renderer.md
> +    licenseKey="non-commercial-and-evaluation">
```suggestion
    <HotTable data={hotData}
      autoWrapRow={true}
      autoWrapCol={true}
      licenseKey="non-commercial-and-evaluation">
```

2023-12-20 13:10 UTC, budnix commented on docs/content/guides/columns/column-header.md
> +const hot = sontable(container, {
```suggestion
const hot = new Handsontable(container, {
```
😅

2023-12-20 13:10 UTC, budnix commented on docs/content/guides/columns/column-moving.md
> +      autoWrapCol={true }
```suggestion
      autoWrapCol={true}
```

2023-12-20 13:10 UTC, budnix commented on docs/content/guides/columns/column-virtualization.md
> +  licenseKey="non-commercial-and-evaluation" />;
```suggestion
  return <HotTable data={data} colWidths={100} width="100%" height={320} rowHeaders={true} colHeaders={true} autoWrapRow={true}
    autoWrapCol={true}
    licenseKey="non-commercial-and-evaluation" />;
```

2023-12-20 13:10 UTC, budnix commented on docs/content/guides/columns/react-hot-column.md
> +    licenseKey="non-commercial-and-evaluation">
```suggestion
    <HotTable data={hotData} 
      autoWrapRow={true}
      autoWrapCol={true}
      licenseKey="non-commercial-and-evaluation">
```

2023-12-20 13:10 UTC, budnix commented on docs/content/guides/getting-started/binding-to-data.md
> +    licenseKey="non-commercial-and-evaluation" />
```suggestion
    <HotTable 
      autoWrapRow={true}
      autoWrapCol={true}
      licenseKey="non-commercial-and-evaluation" />
```

2023-12-20 14:29 UTC, budnix requested changes
I'd say that it looks good but the CI says something different https://github.com/handsontable/handsontable/actions/runs/7276585493/job/19826734582?pr=10677.

2023-12-20 15:37 UTC, evanSe commented
> I'd say that it looks good but the CI says something different https://github.com/handsontable/handsontable/actions/runs/7276585493/job/19826734582?pr=10677.

Cheers, probably syntax error due to how much loc changed

2024-01-02 10:12 UTC, budnix approved these changes

2024-01-02 12:14 UTC, merged