Navigate and edit cells within a range
handsontable/handsontable pull request #10732
Opened 2024-01-16 14:12 UTC by budnix

### Context

The PR adds a new feature: navigation and edit cells within a range.

### How has this been tested?

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/1690

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2024-02-08 16:03 UTC, krzysztofspilka commented
Issue 1: I got into a loop when trying to move the selector with <kbd>TAB</kbd> at the edge of the merge cell. Also, if the column selected is adjacent to a merged cell, the selection is stuck.

https://github.com/handsontable/handsontable/assets/8048526/cb9c5355-6d1b-44b7-874e-8167251670af

https://github.com/handsontable/handsontable/assets/8048526/59740009-9485-4c06-a191-923739d39050

2024-02-08 16:11 UTC, krzysztofspilka commented
Issue 2. To select an item from the select cell type, I first focus on a cell and press <kbd>Space</kbd> twice. Then I move through the menu using <kbd>arrow keys</kbd> and then press <kbd>Enter</kbd> to choose the right value.

Unfortunately, it loses the focus, so when I press <kbd>Tab</kbd>, I end up in the `input` below the grid.

https://github.com/handsontable/handsontable/assets/8048526/a2461c6b-bc92-4c92-8d6c-ab3abca58e4f

2024-02-08 16:15 UTC, krzysztofspilka commented
Issue 3. Connected with issue 1 - the merged cell gets into a loop if you use <kbd>Tab</kbd> key to navigate.

https://github.com/handsontable/handsontable/assets/8048526/2e7f1a40-cd5c-4764-8279-aba34f06a5f3

2024-02-08 16:29 UTC, krzysztofspilka commented
Issue 5. The selection is overlapped by the bottom fixed row if it's close to the bottom edge of the viewport. I moved the selection with <kbd>Tab</kbd> on this video.

https://github.com/handsontable/handsontable/assets/8048526/0f3dae82-7990-4cf3-8c3a-76479a4535d2

2024-02-08 16:36 UTC, krzysztofspilka commented
Issue 6. The selected cells get detached from the focused cell. 

1. Select three or more rows in the first column (with mouse or however).
2. Press <kbd>Tab</kbd> twice
3. Press Shift + ↘︎ (End key)

https://github.com/handsontable/handsontable/assets/8048526/c784ac81-ccd4-48bb-aa05-2704b83a9f98

2024-02-08 16:47 UTC, krzysztofspilka commented
Issue 7. If `tabNavigation={false}` then when I select cells and press <kbd>Tab</kbd> once, then I lose the focus. It's restored after I press that key one more time. Haven't noticed this problem with <kbd>Shift + Tab</kbd>.

https://github.com/handsontable/handsontable/assets/8048526/89618186-ecd8-4d7e-a7af-99fa223f0098

2024-02-09 11:06 UTC, krzysztofspilka commented
- Issue 1: related, to be fixed now
- Issue 2: not related, moved to https://github.com/handsontable/dev-handsontable/issues/1746
- Issue 3: related, to be fixed now
- Issue 4: NOT related but to be fixed now https://github.com/handsontable/dev-handsontable/issues/1747
- Issue 5: not related, moved to https://github.com/handsontable/dev-handsontable/issues/1748
- Issue 6: related, to be fixed now
- Issue 7: Problem with CodeSandbox - to be confirmed

2024-03-20 10:34 UTC, jansiegel requested changes

2024-03-20 10:39 UTC, budnix commented on handsontable/src/selection/highlight/visualSelection.js
> +      // TODO
It is supposed to stay. The code that it marks `broaderCellRange.setHighlight(currentHighlight);` is a workaround and should be moved away from the VisualSelection class in the future.

2024-03-20 10:39 UTC, budnix commented on handsontable/src/pluginHooks.js
> +   * @since 14.2.0
Thanks ... fixed within 92de45b0e8b2c4732af7ed9bf009536dacfcbb01.

2024-03-20 10:40 UTC, jansiegel approved these changes

2024-03-20 15:42 UTC, krzysztofspilka commented
@budnix one thing I noticed that I no longer can use `DELETE` or `BACKSPACE` to remove the content.

1. Open https://codesandbox.io/p/sandbox/vigorous-bouman-5vv2f9?file=%2Fpackage.json
2. Click on any cell
3. Press Delete or Backspace

Result: nothing happens

2024-03-21 08:16 UTC, budnix commented
> @budnix Another thing I noticed is that I cannot use `TAB` to leave the cell in the `empty` column. I'm not sure if it's specific for this [demo](https://codesandbox.io/p/sandbox/vigorous-bouman-5vv2f9?file=%2Fpackage.json) or sth more global.

Solved by adding `autoWrapRow` and `autoWrapCol` https://codesandbox.io/p/sandbox/sparkling-cloud-d9yf4s?file=%2Fsrc%2Findex.tsx%3A173%2C20

2024-03-25 14:06 UTC, merged