Display the numeric renderer's output in the Filters' multi-selection module.
handsontable/handsontable pull request #10756
Opened 2024-01-29 13:24 UTC by jansiegel

### Context
#### [ Work in Progress ]

This PR:
- Adds a new `displayValue` cell meta property
- Implements a new `getDisplayValuesAtCol` method
- Makes the filters' multi-selection module utilize the newly created method
- Sets the new `displayValue` prop in the numeric renderer

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2024-02-05 09:57 UTC, budnix requested changes
I'm not convinced about that `displayValue` option. I know that the purpose of this task is to add support for modifying filter values only for numeric values, but with this shape, it isn't very clear.
The question that comes to my mind or limitation that I found:
 * The value can not be changed in the `cells` function. The `displayValue` property is always overwritten in the numeric renderer; 
 * When the `displayValue` property does not exist, the Filters plugin generates one by calling the numeric renderer by itself. So what is this option for? Kind of read-only and for numeric columns only?
 * Maybe a better idea would be creating renderers for Filters. The same goes for cells. For example, `filtersRenderer` option, or so?

2024-02-05 09:57 UTC, budnix commented on handsontable/src/plugins/filters/__tests__/filtersUI.spec.js
> +      }
```suggestion
      for (let i = 0; i < unifiedColDataSample.length; i++) {
        expect(
          byValueMultipleSelect().element.querySelectorAll('.htCore td')[i].textContent
        ).toBe(`Custom ${unifiedColDataSample[i]}`);
      }
      expect(unifiedColDataSample.length).toBe(6);
```
I'd secure that `for` with one more `expect`.

2024-02-05 09:57 UTC, budnix commented on handsontable/src/helpers/dom/element.js
> +export function renderMockCell(rootDocument, renderFunction, renderArgs) {
Can I ask you to cover that function with a test?

2024-02-05 09:57 UTC, budnix commented on handsontable/src/plugins/filters/ui/multipleSelect.js
> +      if (displayValue) {
When the `displayValue` value is `0` (`false` and maybe others), then it's not rendered. I'd try to render all values except `undefined` and only then return source data.

2024-02-05 09:57 UTC, budnix commented on handsontable/src/renderers/numericRenderer/__tests__/numericRenderer.spec.js
> +  describe('NumericRenderer with Filters', () => {
I'd move this Filters-related test to the Filters plugin tests directory.

2024-02-05 10:00 UTC, budnix commented on handsontable/src/renderers/numericRenderer/numericRenderer.js
> +  cellProperties.displayValue = newValue;
I think that it's not the best idea to change cell meta within the renderer function. The changes disturb the function purity 🤔

2024-02-05 14:31 UTC, jansiegel commented
I went through several approaches to this task, but I'll take any suggestions. As for the questions:

> * The value can not be changed in the `cells` function. The `displayValue` property is always overwritten in the numeric renderer;

Yes. The spec requires the multi-selection component in the Filters dropdown to display the same value that's being rendered in the cells. As we cannot know what the renderer with generate, there's no way to assign this value before it's triggered.

> * When the `displayValue` property does not exist, the Filters plugin generates one by calling the numeric renderer by itself. So what is this option for? Kind of read-only and for numeric columns only?

I had to add this logic because the Filters dropdown display all unique values in the table, and the renderers are run just for the visible part of the dataset. Without this logic, some of the values were being displayed in their "source" form, and some in the "rendered" form.

> * Maybe a better idea would be creating renderers for Filters. The same goes for cells. For example, `filtersRenderer` option, or so?

We can do that, but according the the spec, in this case the `filtersRenderer` should be exact same as the regular `renderer` (and for the other cell types the `filtersRenderer` should return the cell's source value...?)

2024-02-07 10:19 UTC, budnix commented
Maybe I'd suggest adding a new hook for the MultipleSelect component of the Filters plugin. Let's name it `modifyFiltersMultipleSelectValue` hook, for example. This hook would be responsible only for modifying the values presented by that component. There would be one hook for all cell types.

Now, depending on the feature needs you can pass as many arguments as you wish. Usage example:
```js
modifyFiltersMultipleSelectValue(sourceValue, cellType, cellMeta) => {
  let newValue = sourceValue;

  if (cellType === 'numeric') {
    if (isNumeric(newValue)) { // HERE I'd copy the logic from the renderer or move it to separate helper
      const numericFormat = cellProperties.numericFormat;
      const cellCulture = numericFormat && numericFormat.culture || '-';
      const cellFormatPattern = numericFormat && numericFormat.pattern;
      const className = cellProperties.className || '';
      const classArr = className.length ? className.split(' ') : [];

      if (typeof cellCulture !== 'undefined' && !numbro.languages()[cellCulture]) {
        const shortTag = cellCulture.replace('-', '');
        const langData = numbro.allLanguages ? numbro.allLanguages[cellCulture] : numbro[shortTag];

        if (langData) {
          numbro.registerLanguage(langData);
        }
      }

      numbro.setLanguage(cellCulture);

      newValue = numbro(newValue).format(cellFormatPattern || '0');
    } 
  }
  // PLACE FOR OTHER CELL TYPES

  return newValue;
}
```

2024-02-08 14:30 UTC, budnix commented on handsontable/src/plugins/filters/__tests__/filtersUI.spec.js
> +      }
I assume that there is a chance a developer (unintentionally, by accident) can edit `for` loop or edit an array in a way that there won't be any iteration. Then the test will pass, as no `expect` is called.

2024-02-09 09:07 UTC, budnix requested changes
It looks good. I left one comment with suggestions to be considered. And I wonder, would it be possible to pass a complete cellMeta object as a second argument? It would be better for the user not to have to figure out a new data structure. They already know/use cellMeta objects in other hooks or methods.

2024-02-09 09:09 UTC, budnix commented
Ah, and I almost forgot. Can you add a TypeScript definition for `modifyFiltersMultiSelectValue` hook? 😄

2024-02-09 10:04 UTC, budnix approved these changes

2024-02-09 11:03 UTC, merged