Update HyperFormula version in guide
handsontable/handsontable pull request #10815
Opened 2024-02-23 13:07 UTC by adrianspdev

### Context
This PR includes information about new version of HyperFormula in documentation, and update HyperFormula to latest version in package.json

### How has this been tested?
Locally

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/1615

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [x] Update HyperFormula guide
- [x] Change version of hyperformula i package.json to "^2.6.2"

[skip changelog]

2024-02-26 10:27 UTC, evanSe approved these changes

2024-02-26 10:28 UTC, evanSe requested changes
@adrianspdev could you also add an entry for Handsontable 14.2.0 which is not out yet, we wont deploy this doc change until 14.2 release.

2024-02-27 11:36 UTC, adrianspdev commented
> @adrianspdev could you also add an entry for Handsontable 14.2.0 which is not out yet, we wont deploy this doc change until 14.2 release.

done

2024-03-20 09:45 UTC, evanSe submitted a review, later dismissed

2024-03-20 11:05 UTC, evanSe approved these changes

2024-03-20 11:25 UTC, merged