Add algolia search to documentation
handsontable/handsontable pull request #10877
Opened 2024-03-27 10:14 UTC by adrianspdev

### Context
This PR includes new documentation search box with algolia

### How has this been tested?
Locally

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/1780

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [x] Update the documentation to use Algolia for search.
- [x] Search bar and results interface are visually integrated with the existing documentation website design.

[skip changelog]

2024-03-27 11:17 UTC, budnix requested changes
@adrianspdev I deployed the changes to the [staging](https://dev.handsontable.com/docs/javascript-data-grid/), but it seems not working. There are plenty of errors coming into the console when I type something. Also, the styling appears to be broken. Could you check that?
![image](https://github.com/handsontable/handsontable/assets/571316/f22befea-afe2-406c-9d9c-0b9bd43b82fe)

2024-03-27 13:46 UTC, budnix submitted a review, later dismissed

2024-03-28 06:59 UTC, magierg submitted a review, later dismissed

2024-06-10 09:09 UTC, evanSe commented
This was merged as part of another pull request, @adrianspdev closing

2024-06-10 09:09 UTC, closed without merging