Add structured data to docs
handsontable/handsontable pull request #10880
Opened 2024-03-28 13:37 UTC by adrianspdev

### Context
This PR includes ld+json script with additional SEO information

### How has this been tested?
Locally

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2024-04-03 08:10 UTC, budnix approved these changes
All good 👍 I left one note to consider.

2024-04-03 08:10 UTC, budnix commented on docs/.vuepress/theme/components/SchemaStructuredData.vue
> +const timezone = require('dayjs/plugin/timezone');
Is there any chance of using `import` here? It looks a bit odd to see ESM and CommonJS mixed together 😄

2024-04-05 07:13 UTC, evanSe reviewed
Could you cross reference with the original json ld example with the actual generated examples, some improvements could be made.

2024-04-05 07:13 UTC, evanSe commented on docs/.vuepress/theme/components/SchemaStructuredData.vue
> +        name: this.meta_data.title || null,
Is it possible to have name, headline and description to be a bit more descriptive like the original issue example json ld

2024-04-10 09:07 UTC, budnix submitted a review, later dismissed

2024-04-12 10:22 UTC, evanSe approved these changes

2024-04-17 11:44 UTC, budnix requested changes
I tried to push the changes on staging but it throws a lot of errors https://github.com/handsontable/handsontable/actions/runs/8721068534/job/23923981279?pr=10880. Can you check that?

2024-04-17 13:14 UTC, budnix approved these changes
I don't know if it's ok that the structure is generated by JS only. if so, it's ok for me.

2024-04-18 07:33 UTC, budnix approved these changes

2024-04-25 09:27 UTC, merged