feat: change release-notes to the changelog #1956
handsontable/handsontable pull request #11074
Opened 2024-07-09 06:14 UTC by Skoczowianin

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2024-07-10 08:26 UTC, budnix requested changes
Some changes need correction. Also, the link "Changelog" in the Docs header does not work (404). Can you check that? 
![Zrzut ekranu 2024-07-10 o 10 25 16](https://github.com/handsontable/handsontable/assets/571316/ddf39dfb-4bc5-4459-a3b5-d06c128fd231)

2024-07-10 08:26 UTC, budnix commented on docs/docker/redirects.conf
> +rewrite ^/docs/$framework/release-notes/?$ /docs/$framework/changelog/ permanent;
I'd move this line to line 124 and change it to
```
rewrite ^/docs/(javascript|react)-data-grid/release-notes/?$ /docs/$framework/changelog/ permanent;
```

2024-07-10 12:23 UTC, budnix approved these changes
👍

2024-07-10 12:51 UTC, merged

2024-07-15 12:34 UTC, magierg commented
fix verified on staging