Remove dtslint
handsontable/handsontable pull request #11079
Opened 2024-07-10 11:16 UTC by adrianspdev

### Context
This PR includes lint improvements

### How has this been tested?
Locally

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/1981

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [x] Remove dtslint and tslint and adjust it in eslint

[skip changelog]

2024-07-10 11:37 UTC, budnix requested changes
Correct me if I'm wrong, but shouldn't the linter show an error? I made a typo in the `handsontable/types/eventManager.d.ts` file, replaced the `string` argument type with `strin`, and nothing happened 🤔 shouldn't calling `npm run type-lint` catch this?

2024-07-10 11:38 UTC, evanSe approved these changes

2024-07-10 13:01 UTC, evanSe commented
> Correct me if I'm wrong, but shouldn't the linter show an error? I made a typo in the `handsontable/types/eventManager.d.ts` file, replaced the `string` argument type with `strin`, and nothing happened 🤔 Shouldn't calling `npm run type-lint` catch this?

It will not catch this, nor did it before. In theory, we may be able to catch this with extra linting rules but I may be wrong.

I tested the previous vs this pull request and its the same behavior, if you go and break a class such a `export default clastesting` it will throw error.

2024-07-11 07:20 UTC, budnix approved these changes

2024-07-11 08:20 UTC, evanSe approved these changes

2024-07-11 08:48 UTC, merged