Fix autofill corner style for new themes
handsontable/handsontable pull request #11330
Opened 2024-12-20 11:51 UTC by adrianspdev

### Context
This PR includes fixes for autofill corer styles

### How has this been tested?
Loaclly

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/2143

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/react-wrapper`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [x] Fix autofill handle styles

2024-12-23 08:48 UTC, jansiegel requested changes
One of the Walkontable tests seems to be failing

```
1) WalkontableBorder corner (modern themes) should render corner with proper styles
1.1) Expected 101 to equal 98.
    Error: Expected 101 to equal 98.
        at <Jasmine>
```

2025-01-03 08:45 UTC, budnix approved these changes

2025-01-08 09:22 UTC, jansiegel requested changes

2025-01-08 09:22 UTC, jansiegel commented on handsontable/src/3rdparty/walkontable/src/selection/border/border.js
> +          }
Maybe we could cache the duplicated calculation for better readability?

```suggestion
          const cornerTopPosition = Math.floor(
            top + height + this.cornerCenterPointOffset - cornerHalfHeight - cornerBorderCompensation
          );

          if (isClassicTheme) {
            // styles for classic theme
            this.cornerStyle.top = `${cornerTopPosition}px`;
            this.cornerStyle.borderBottomWidth = 0;
          } else {
            // styles for ht-theme
            this.cornerStyle.top = `${cornerTopPosition - 1}px`;
          }
```

2025-01-09 07:42 UTC, jansiegel commented
@adrianspdev I think the Argos fail is intentional, but could you make sure?

2025-01-09 11:57 UTC, jansiegel approved these changes

2025-01-09 11:58 UTC, merged