Fix calculation of the number of columns.
handsontable/handsontable pull request #7243
Opened 2020-09-02 15:59 UTC by Gwe-n

Fix #7217

### Context

The `calculate()` function did not take into account the second column of the handsontable type.

This is related to the fact that for the first column 
`columnWidth` === `viewportWidth`

### How has this been tested?

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7217

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

2020-09-03 07:38 UTC, AMBudnik commented
Hi @Gwe-n 

thank you for sharing the pull request and signing our CLA.
Could you also add a test for this change? We'd like to avoid any possible misalignments in the future.

2020-09-09 12:49 UTC, Gwe-n commented
@AMBudnik Done !

2020-09-09 13:03 UTC, AMBudnik commented
Thank you.

2021-03-19 09:56 UTC, wszymanski requested changes
Hello, @Gwe-n. Thanks for your effort. Nice to see extra test and code which works. However, I'm afraid that your solution fix some case symptomatically, but it may not touch the source of the problem.

It seems that `getViewportWidth` method (and deeper) is the place where we should look for the problem.

1. First config (2 columns) with result (`50px`).

```js
data: [
  [1, 2, 3, 4],
  [5, 6, 3, 5],
  [8, 9, 3, 5]
],
colHeaders: true,
rowHeaders: true,
columns: [{
  type: "handsontable",
  handsontable: {
    data: [
      [3, 4],
      [6, 7]
    ],
    colHeaders: true,
  },
}, {}, {}, {}]
```

![Screenshot 2021-03-19 at 10 57 42](https://user-images.githubusercontent.com/141330/111763002-f2d3a180-88a1-11eb-954d-f4f6933ea83c.png)

2. Second config (3 columns) with result (`1866px`).

```js
data: [
  [1, 2, 3, 4],
  [5, 6, 3, 5],
  [8, 9, 3, 5]
],
colHeaders: true,
rowHeaders: true,
columns: [{
  type: "handsontable",
  handsontable: {
    data: [
      [3, 4, 3],
      [6, 7, 4]
    ],
    colHeaders: true,
  },
}, {}, {}, {}]
```

![Screenshot 2021-03-19 at 10 52 19](https://user-images.githubusercontent.com/141330/111762320-31b52780-88a1-11eb-8c41-fab6ddc94223.png)


It returns completely different results for Handsontable (in Handsontable) with different number of columns. Why? It should be deeply debugged. Please let me know WDYT about it.

2021-09-27 11:46 UTC, AMBudnik commented
It seems that at the moment, the work on that pull request is on hold as we did not get any new updates for months. Considering feedback from @wszymanski we cannot merge the changes as they are proposed.

Please notify me @Gwe-n if you would like to continue.

2021-09-27 11:46 UTC, closed without merging