Change overflow visible to scroll
handsontable/handsontable pull request #7279
Opened 2020-09-17 07:46 UTC by Gwe-n

Fix #7259

### Context
When the window has a fixed size, there's not enough data and HOT's parent doesn't have width, height, and overflow
The `overflow: visible` adds a scroll to the table

### How has this been tested?

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7259 

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

2020-09-17 08:01 UTC, AMBudnik commented
Thank you for reporting @Gwe-n and referencing to my issue.

As each of the changes in the code should be covered by at least one test could I ask you to add one? That would help us a lot.

2020-09-17 13:53 UTC, wojciechczerniak commented
https://codesandbox.io/s/handsontableexamples-pull-request-forked-wqp9l

Headers do not stick to the screen edge and scrollbars are shown

Wrong:
![Screenshot 2020-09-17 at 15 50 04](https://user-images.githubusercontent.com/4718998/93480288-90ebac80-f8fd-11ea-8a90-9f2f47107522.png)

Correct, headers are sticky to the edge, no unnecessary scrollbars.
![Screenshot 2020-09-17 at 15 52 25](https://user-images.githubusercontent.com/4718998/93480516-d14b2a80-f8fd-11ea-9f1d-d31cc4ed66e8.png)

2020-09-17 15:41 UTC, Gwe-n commented
@wojciechczerniak I looked at your link, and I didn't get it. Is my commit incorrect and/or causes a regression?

2020-09-23 13:31 UTC, AMBudnik commented
Hey @Gwe-n it seems that we get this effect when we use your changes in the code.

2020-09-29 13:39 UTC, Gwe-n commented
Are you sure the problem was not already there? 
When I inspect the deployed code, I can't find my modification, I have the impression that the deployment doesn't work.

![Capture d’écran 2020-09-29 à 15 38 35](https://user-images.githubusercontent.com/66947157/94565753-e31bbe80-0269-11eb-9734-278a9abfc8ce.png)

Moreover, in the ticket https://github.com/handsontable/handsontable/issues/7259 
the correct behaviour described here https://jsfiddle.net/AMBudnik/n0ef5k4g/
has a non-sticky header.

2020-09-30 11:16 UTC, AMBudnik commented
Hi @Gwe-n please try to scroll to right using this demo https://codesandbox.io/s/handsontableexamples-pull-request-forked-hy8p8 

Here's what I get using Chrome

![issue](https://user-images.githubusercontent.com/10757813/94678681-27b56180-031f-11eb-934d-65f3542ab567.gif)


that's why we always ask for tests and we also try to add as many scenarios as necessary.

2020-11-02 16:19 UTC, Gwe-n commented
Hi @AMBudnik indeed, you were right. I pushed a new suggestion

![Enregistrement de l’écran 2020-11-02 à 17 17 27](https://user-images.githubusercontent.com/66947157/97891779-80698700-1d2f-11eb-8b0d-ddaee27d6426.gif)

Please let me know if this is acceptable to you

2020-11-03 09:04 UTC, AMBudnik commented
Thank you for sharing the update @Gwe-n

2021-03-24 11:16 UTC, wszymanski requested changes
Hello @Gwe-n, thanks for your effort, again. It works 👏  It also have needed test 🙂  Some e2e would be also welcome, but I won't push you to doing it. However, I have some questions.

I have one needed change. Could you rename file from `bottomLeftCorner.spec.js` to `bottomLeftCorner.unit.js`. Without it, the test won't be executed.

2021-03-24 11:16 UTC, wszymanski commented on src/3rdparty/walkontable/test/unit/overlay/bottomLeftCorner.spec.js
> +import TopLeftCornerOverlay from 'walkontable/overlay/topLeftCorner';
```suggestion
import { registerOverlayOnce, BottomLeftCornerOverlay, TopLeftCornerOverlay } from 'walkontable/overlay';
```

2021-03-24 11:16 UTC, wszymanski commented on src/3rdparty/walkontable/test/unit/overlay/bottomLeftCorner.spec.js
> +    Overlay.registerOverlay('top_left_corner', TopLeftCornerOverlay);
Is registration really needed, especially for `TopLeftCornerOverlay`? Btw. a way how overlays are registered has been changed. Could you adapt it for new codebase?

2021-03-24 11:16 UTC, wszymanski commented on src/3rdparty/walkontable/src/overlay/bottomLeftCorner.js
> +    this.overlayRoot = null;
Is really this change needed? I would not change it for consistency with other overlays.

2021-09-27 11:43 UTC, AMBudnik commented
As there are no further updates on this pull request for months and our issues haven't been addressed, I need to close this pull request.

@Gwe-n, if you would like to continue the work, please let me know.

2021-09-27 11:43 UTC, closed without merging