issue https://github.com/handsontable/handsontable/issues/5640
handsontable/handsontable pull request #7284
Opened 2020-09-21 13:46 UTC by fewensa

remove

KEY_CODES.COMMAND_LEFT
KEY_CODES.COMMAND_RIGHT
KEY_CODES.COMMAND_FIREFOX

in isCtrlMetaKey function

### Context

fix IME - Unable to release selected

I'm remove COMMAND_LEFT/COMMAND_RIGHT/COMMAND_FIREFOX keys to fix this bug.
in unicode.js I found `isCtrlKey` function, this function is never used. but this function also maybe can fix this bug.

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/helpers/unicode.js#L110-L127

But I'm not use it, because in issue https://github.com/handsontable/handsontable/issues/5640 have a referencee issue https://github.com/handsontable/handsontable/issues/6012 , so Mac OS have the same issue. so I'm remove COMMAND_LEFT/COMMAND_RIGHT/COMMAND_FIREFOX keys in `isCtrlMetaKey`.

This is not a great solution, because the `pressedKeys` also have COMMAND_LEFT/COMMAND_RIGHT/COMMAND_FIREFOX keycode, but this is very simple way to fix this bug.

I check all call there code.

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/editorManager.js#L375-L380

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/utils/keyStateObserver.js#L75-L79

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/columnSorting/columnSorting.js#L766-L774

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/columnSorting/columnSorting.js#L783-L796

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/plugins/multiColumnSorting/multiColumnSorting.js#L249-L266

https://github.com/handsontable/handsontable/blob/0ec29f9cab9e0d9df1af99287c1211e87779737a/src/selection/selection.js#L159-L173

I'm sorry, I'm not sure this change have another effect. if it's ok, I wish it's working.

### How has this been tested?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/5640
2. https://github.com/handsontable/handsontable/issues/6012

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

2020-09-22 11:24 UTC, AMBudnik commented
Hi @fewensa 

thank you for sharing the pull request. Could you also sign our [CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1) and add a test that checks the changes?

reference: [contributing guide](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

2020-09-23 15:29 UTC, fewensa commented
Hi @AMBudnik , I'm posted this form, and  so sorry, I don't known how to test it, because I don’t know how to use e2e test.

2020-09-23 15:31 UTC, fewensa commented
Hi @AMBudnik  I'm posted this form, and so sorry I don't know how to use e2e

2020-09-24 09:22 UTC, AMBudnik commented
Thank you for signing the CLA.

2021-03-22 11:29 UTC, wszymanski requested changes
Hello, @fewensa. It seems that investigation [done by you](https://github.com/handsontable/handsontable/issues/5640#issuecomment-695206792) is proper.

The change suggested by you is fixing mentioned problems. However, it is not good solution for us. It definitely removes part of functionality from our code. It seems to be intended that we may do some actions by removed meta keys. Without them we have lot of use cases which doesn't work and [tests](https://handsontable.com/docs/8.3.2/tutorial-testing.html) show it.

I'm sorry, but we can't provide solution which affect regression of another part of functionality ie. non-contiguous selection. We are open for new ways of resolving existing problems.

2021-09-20 08:51 UTC, AMBudnik commented
Again thank you for all the effort you took to investigate the subject @fewensa 
However, as @wszymanski wrote at the moment we cannot merge the proposed changes changes.

2021-09-20 08:51 UTC, closed without merging