Misalignment correction when zooming
handsontable/handsontable pull request #7298
Opened 2020-09-28 12:48 UTC by oskrd

### Context
When the zoom is changed in the browser (zoom in more than 150% and zoom out less than 80%) HoT will get misalignment between fixed and movable columns.

This is an [adaptation of the larvanitis proposal](https://github.com/handsontable/handsontable/issues/3118#issuecomment-384305625), I manually just tested.

### How has this been tested?
* Changing the zoom from 25% to 500%.
* Tested in browsers Google Chrome, Edge Chromium, Mozilla Firefox

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
[3118](https://github.com/handsontable/handsontable/issues/3118)

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

2020-09-29 07:06 UTC, AMBudnik commented
Thank you for sharing the pull request @oskrd 
Could you also add a test scenario for the changes?

2020-10-02 08:24 UTC, AMBudnik commented
This PR has been marked as 'Ready for review' without the tests.

2020-10-12 16:48 UTC, aarondfrancis commented
Would love to see this merged! Not being able to zoom has caused us a lot heartache. Thanks @oskrd!

2021-03-23 11:51 UTC, wszymanski requested changes
Hello,

thanks for your effort and sorry for late answer. Although it provide some solution for the problem it has also side effects. We have `85` failing tests for the branch. After investigation I can see that problem is not related to the way how tests are written. For example, the code changes a size provided by `ManualRowResize` plugin for zoom set to `100%`.

Example config.

```js
data: Handsontable.helper.createSpreadsheetData(5, 5),
rowHeaders: true,
manualRowResize: [50, 50, 50, 50, 50, 50],
```

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/141330/112141830-1bc3a180-8bd6-11eb-8a9f-28d916677c03.png"></td>
    <td><img src="https://user-images.githubusercontent.com/141330/112141509-a8219480-8bd5-11eb-9c40-a821321bfa76.png"></td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/141330/112141518-a9eb5800-8bd5-11eb-8220-7bb4c5527016.png"></td>
    <td><img src="https://user-images.githubusercontent.com/141330/112141514-a952c180-8bd5-11eb-973e-c23a241006c7.png"></td>
  </tr>
</table>

It's not definitely a way how we can provide size for table.

2021-03-23 12:21 UTC, wszymanski commented on src/3rdparty/walkontable/src/renderer/table.js
> +          TR.style.height = `${rowHeight - 1}px`;
```suggestion
          TR.style.height = `${rowHeight}px`;
```

Maybe removing `1px` will help? There should be done further investigation.

2021-05-30 17:25 UTC, oskrd commented
> Hi @oskrd, This PR cannot be merged as it is developed. As @wszymanski spotted, it produces some issues.
> This topic itself is outside of the scope of Q2/2021, so we did not continue the investigation.

Hello again @AMBudnik, I read this comment in some related issues

> This issue is closed temporarily. It will be reopened for development as it became a part of Interoperability problems using zoom/system UI scaling and some core features task reported at #7527
> 
> I will make sure to inform everyone interested in this topic after the official fix.
> 
> Please feel welcome to makes any comments on this issue. And if you experience similar behaviour feel free to contact me at support@handsontable.com

So, have you planned work on the fix of this set of problems in Q3/Q4 already?

2021-05-31 09:49 UTC, AMBudnik commented
As you rightly spotted, @oskrd we have gathered the zoom-related issues in one place https://github.com/handsontable/handsontable/issues/7527 to plan the work on the subject in the future easily. However, the development on this subject hasn't been scheduled yet. Surely, once we plan to work on zoom-related topics, we will recheck all the related subjects and feedback from the community.

Ps. here, in the projects tab, https://github.com/handsontable/handsontable/projects, you can check what we are doing now and what's in the scope for the next releases.

2021-09-27 11:39 UTC, AMBudnik commented
Hi @oskrd 

I am afraid that till we be able to discuss the details reported by @wszymanski that are blocking us from merging your changes I need to keep this PR closed.
Please feel free to contact us anytime when you will be ready.

2021-09-27 11:39 UTC, closed without merging