Remove optional marking for params in setDataAtCell [DOCS]
handsontable/handsontable pull request #7346
Opened 2020-10-18 14:56 UTC by scarletfog

### Context
Two params are no longer optional, remove the misleading information.

### Types of changes

- [ ] Improvement in the documentation

### Related issue(s):
1. https://github.com/handsontable/docs/issues/181

2020-10-18 16:31 UTC, wojciechczerniak requested changes
No

2020-10-19 08:33 UTC, AMBudnik commented
OK, so I think that we can close this PR and chat about possible code samples at https://github.com/handsontable/docs/issues/181

2020-10-19 08:47 UTC, scarletfog commented
@AMBudnik let's keep it. I will use it to add examples

2021-03-12 10:49 UTC, wojciechczerniak commented
For adding examples we should create a new PR.

2021-03-12 10:49 UTC, closed without merging