Fix a problem, where removing rows/columns did not change the selection size, which might have exceeded the table limits.
handsontable/handsontable pull request #7373
Opened 2020-11-04 15:17 UTC by jansiegel

### Context
This PR should fix a problem described in #7337. Although this bug is a part of a larger problem/need for an enhancement, @wojciechczerniak and I decided to do the minimal approach first, as modifying the way selections act after CRUD actions would inevitably contain a breaking change.

### How has this been tested?
Added 2 test cases.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7337 

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

2020-11-10 10:43 UTC, budnix requested changes
I think that selection modification overall should be moved to the https://github.com/handsontable/handsontable/blob/feature/issue-7337-simplified/src/core.js#L707. There is already logic that uses `selectCell` API (it's not working for headers after introducing negative coordinates). Maybe instead of modifying internal structures like `selection.selectedByRowHeader.add(selection.getLayerLevel());`, we can use the public API? 

Pseudocode:
```
if (selection.isSelected()) {
  const isSelectedByCorner = selection.isSelectedByCorner();
  const isSelectedByRowHeader = selection.isSelectedByRowHeader();
  const isSelectedByColumnHeader = selection.isSelectedByColumnHeader();
  const minZeroClamp = (value) => Math.max(value, 0);
...
if (selectionChanged) {
  if (isSelectedByCorner) {
    instance.selectAll(true);
  } else if (isSelectedByRowHeader) {
    instance.selectRows(minZeroClamp(fromRow), minZeroClamp(toRow));
  } else if (isSelectedByColumnHeader) {
    instance.selectColumns(minZeroClamp(fromCol), minZeroClamp(toCol));
  } else {
    instance.selectCell(fromRow, fromCol, toRow, toCol);
  }
}
```

Within the changes, only the last selection is trimmed. What about trimming non-contiguous selection?
![Kapture 2020-11-10 at 11 47 59](https://user-images.githubusercontent.com/571316/98664413-a18f3080-234a-11eb-87bf-abead95809c4.gif)

2020-11-10 10:43 UTC, budnix commented on src/core.js
> +      const trimSelectionToTableSize = () => {
Can I ask you to move the code to the `adjustRowsAndCols` (https://github.com/handsontable/handsontable/blob/feature/issue-7337-simplified/src/core.js#L707) method? There is already an implemented mechanism for cell selection. I think that there is the best place for extending that functionality.

2020-11-10 10:43 UTC, budnix commented on src/core.js
> +          selection.selectedByRowHeader.add(selection.getLayerLevel());
I think It's a bad idea to modify the internal props (like `selectedByRowHeader`) of the Selection class from the outside. Can you move the logic to the Selection class?

2021-01-28 17:00 UTC, aninde commented
This has been added to the QA pipeline and the review is still ongoing. How can I help?

2023-04-05 07:34 UTC, jansiegel commented
Closing for being inactive for 2+ years.
To be checked if still applicable when going back to #7337.

2023-04-05 07:34 UTC, closed without merging