Adding isDeprecated hook definition
handsontable/handsontable pull request #7407
Opened 2020-11-20 13:07 UTC by AMBudnik

### Context

This pull request covers fixes for issues listed in #7400 and a small fix for #7399. All the issue are related to one of the following scenarios

* typos in parameters
* missing return types
* incorrect behavior

For more details visit #7400 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7399
2. #7400

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

2020-12-09 14:37 UTC, wojciechczerniak requested changes

2020-12-09 14:37 UTC, wojciechczerniak commented on handsontable.d.ts
> +      afterTrimRow?: (currentTrimConfig: number[], destinationTrimConfig: number[], actionPossible: boolean, stateChanged: boolean) => void | bolean;
bolean -> boolean

But anyway, `after*` hooks should not return anything.

2020-12-09 14:37 UTC, wojciechczerniak commented on handsontable.d.ts
> +      afterUntrimRow?: (currentTrimConfig: number[], destinationTrimConfig: number[], actionPossible: boolean, stateChanged: boolean) => void | boolean;
`after*` hooks should return `void`. Anything else will be ignored/

2020-12-09 14:37 UTC, wojciechczerniak commented on handsontable.d.ts
> +      beforeFilter?: (conditionsStack: plugins.FiltersPlugin.ColumnConditions[]) => boolean;
`beforeFilter` is not forcing boolean result, may not return anything. Keep `void`

2020-12-10 08:41 UTC, AMBudnik commented
Hey @wojciechczerniak thank you for reviewing my PR. 
I was told to share it with @scarletfog but I've attached the changes so @scarletfog can work on the improved version.

2020-12-10 09:58 UTC, wojciechczerniak requested changes

2020-12-10 09:58 UTC, wojciechczerniak commented on handsontable.d.ts
> +      afterTrimRow?: (currentTrimConfig: number[], destinationTrimConfig: number[], actionPossible: boolean, stateChanged: boolean) => void | boolean;
One left

2020-12-10 10:02 UTC, AMBudnik commented on handsontable.d.ts
> +      afterTrimRow?: (currentTrimConfig: number[], destinationTrimConfig: number[], actionPossible: boolean, stateChanged: boolean) => void | boolean;
done

2020-12-10 10:32 UTC, wojciechczerniak submitted a review, later dismissed
🏆

2020-12-10 11:04 UTC, scarletfog commented
@wojciechczerniak just a small change within b44ff0fd098a9372480a32218ff31dd6ea5db83b after our discussion on slack.

2020-12-10 11:05 UTC, wojciechczerniak approved these changes
@scarletfog good catch 👍

2020-12-10 12:39 UTC, wojciechczerniak requested changes

2020-12-10 12:39 UTC, wojciechczerniak commented on handsontable.d.ts
> +      afterColumnMove?: (movedColumns: number[], finalIndex: number, dropIndex: number | undefined, movePossible: boolean, orderChanged: boolean) => void;
`afterRowMove` is using `void`

2020-12-10 12:39 UTC, wojciechczerniak commented on handsontable.d.ts
> +      beforeColumnMove?: (movedColumns: number[], finalIndex: number, dropIndex: number | undefined, movePossible: boolean) => void | boolean;
`beforeRowMove` is using `void`

2020-12-10 16:10 UTC, wojciechczerniak approved these changes
🍪

2020-12-11 09:43 UTC, merged