Add Changes Observable for index translations
handsontable/handsontable pull request #7528
Opened 2021-02-16 11:08 UTC by budnix

### Context

The PoC adds Changes Observable feature which allows reacting to the index changes. The Nested Headers tree then is modified by the changes calculated in the index translations.

_WIP_

### How has this been tested?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6879
2.
3.

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-04-13 13:06 UTC, krzysztofspilka commented
Changed the title to better reflect the nature of this task as in fact it's not a bug fix but a new feature.

2021-04-19 12:01 UTC, wszymanski approved these changes
Good job 👏 The code looks very promising! I have just minor suggestions.

2021-04-19 12:22 UTC, wszymanski requested changes
Shouldn't both columns be selected when `shift` key is pressed? What about unhiding elements? Should `unhide column` be visible when `ContextMenu` plugin is enabled?

![shift](https://user-images.githubusercontent.com/141330/115235482-8951e780-a11a-11eb-8fc4-2ff90d4dc33c.gif)

2021-04-19 12:35 UTC, wszymanski commented
It's not regression. Shouldn't unhiding work for all levels?

<img width="383" alt="Screenshot 2021-04-19 at 14 31 37" src="https://user-images.githubusercontent.com/141330/115236720-ffa31980-a11b-11eb-88ec-06ea1a2636c4.png">
<img width="394" alt="Screenshot 2021-04-19 at 14 31 48" src="https://user-images.githubusercontent.com/141330/115236738-03cf3700-a11c-11eb-92c9-0dc5efb6e382.png">

2021-04-19 14:51 UTC, wojciechczerniak commented
> It's not regression and probably is beyond the task scope (@wojciechczerniak?). Shouldn't unhiding work for all levels?

IMO it should

2021-04-20 08:02 UTC, budnix commented on handsontable.d.ts
> +      op: 'replace' | 'insert' | 'remove';
I think that the `op` (operation) name reflects better the essence of changes that happened in the index array. I'd leave it as it is.

2021-04-20 08:08 UTC, budnix commented on src/core.js
> -    instance.columnIndexMapper = null;
I'm sure that if you destroy the Handsontable and remove the reference to its instance all objects would be removed. But, yeah I can agree that `null`-ing that props would decrease overall memory footprint in cases when the developer forgot to remove the reference to the destroyed instance. 

I'll revert that change 😅

2021-04-20 08:16 UTC, budnix commented on src/plugins/nestedHeaders/__tests__/stateManager/nodeModifiers/index.unit.js
> +    // it('should call internal action and return modification results', () => {
Good catch! 💪  This test is redundant and refers to the code before the code refactor.

Done in https://github.com/handsontable/handsontable/pull/7528/commits/2e2f8adfca651e593fbd3c0ebdeef1a32cc760c4

2021-04-20 08:16 UTC, budnix commented on src/core.js
> -    instance.columnIndexMapper = null;
Done in https://github.com/handsontable/handsontable/pull/7528/commits/2e2f8adfca651e593fbd3c0ebdeef1a32cc760c4

2021-04-20 08:18 UTC, budnix commented
> Shouldn't both columns be selected when `shift` key is pressed? What about unhiding elements? Should `unhide column` be visible when `ContextMenu` plugin is enabled?
> 
> ![shift](https://user-images.githubusercontent.com/141330/115235482-8951e780-a11a-11eb-8fc4-2ff90d4dc33c.gif)

You're right! I'll fix that. Eagle Eye!

2021-04-20 08:20 UTC, budnix commented
> It's not regression and probably is beyond the task scope (@wojciechczerniak?). Shouldn't unhiding work for all levels?
> 
> <img alt="Screenshot 2021-04-19 at 14 31 37" width="383" src="https://user-images.githubusercontent.com/141330/115236720-ffa31980-a11b-11eb-88ec-06ea1a2636c4.png">
> 
> <img alt="Screenshot 2021-04-19 at 14 31 48" width="394" src="https://user-images.githubusercontent.com/141330/115236738-03cf3700-a11c-11eb-92c9-0dc5efb6e382.png">

Of course, the context menu should work better when the nested headers are enabled. As you mentioned it's out of the scope for this PR. I'll create a separate issue for this.

2021-04-20 11:18 UTC, budnix commented
> Shouldn't both columns be selected when `shift` key is pressed? What about unhiding elements? Should `unhide column` be visible when `ContextMenu` plugin is enabled?
> 
> ![shift](https://user-images.githubusercontent.com/141330/115235482-8951e780-a11a-11eb-8fc4-2ff90d4dc33c.gif)

Fixed within https://github.com/handsontable/handsontable/pull/7528/commits/420da76ea13e6994f700f68c6fc9110900e091e9.

2021-04-20 13:51 UTC, wszymanski approved these changes

2021-04-23 15:52 UTC, aninde requested changes
A lot of positive changes. It was really hard for me to find something untested. With difficulty, I found one unhandled case.
But first, the good news:
- Autofill borders are displayed in full and flies everywhere where it should. https://github.com/handsontable/handsontable/issues/6900
Demo: https://jsfiddle.net/q2wkrx79/
![awesomeautofill](https://user-images.githubusercontent.com/30186818/115896723-03a4a380-a45c-11eb-8bfc-623f35dfc4e6.gif)

- headers display correctly when nested headers work with hiddenColumns https://github.com/handsontable/handsontable/issues/6879
Demo: https://jsfiddle.net/2aLufc7m/
![Screenshot 2021-04-23 at 17 13 44](https://user-images.githubusercontent.com/30186818/115897001-49fa0280-a45c-11eb-8d32-79f743faa830.png)

- nestedHeaders support noncontinuous selection, even in the complex cases https://github.com/handsontable/handsontable/issues/4964
Demo: https://jsfiddle.net/mrbd3a9o/
![4964-fixed](https://user-images.githubusercontent.com/30186818/115896814-1a4afa80-a45c-11eb-9492-05437bab1348.gif)

- Headers are displayed even though hiding and hiding the column https://github.com/handsontable/handsontable/issues/6879
Demo: https://jsfiddle.net/gbmtwdch/

Unfortunately, I have to mention the unhandled case.

- Bug reported in https://github.com/handsontable/handsontable/issues/7160 is fixed but only for the first use.

When you do hide row operation - horizontal scroll once that's ok. When you execute this reproduction twice, the error described in the issue comes back. 
**Reproduction:** 
1. Hide the first line (A1). 
2. Scroll horizontally to the rightmost but without clicking on the scrollbars
3. Scroll back to the beginning of the table. 
4. Hide the first line (it is now A2). Scroll right. 
The same error appears in the console as before the fix.
Demo https://jsfiddle.net/f1pscmgy/2/
![7160-PR7528](https://user-images.githubusercontent.com/30186818/115897083-58e0b500-a45c-11eb-8501-cce06a1ab10a.gif)

2021-04-26 10:46 UTC, budnix commented
> Unfortunately, I have to mention the unhandled case.
> 
> * Bug reported in #7160 is fixed but only for the first use.
> 
> When you do hide row operation - horizontal scroll once that's ok. When you execute this reproduction twice, the error described in the issue comes back.
> **Reproduction:**
> 
> 1. Hide the first line (A1).
> 2. Scroll horizontally to the rightmost but without clicking on the scrollbars
> 3. Scroll back to the beginning of the table.
> 4. Hide the first line (it is now A2). Scroll right.
>    The same error appears in the console as before the fix.
>    Demo https://jsfiddle.net/f1pscmgy/2/
>    ![7160-PR7528](https://user-images.githubusercontent.com/30186818/115897083-58e0b500-a45c-11eb-8501-cce06a1ab10a.gif)

@aninde Thanks for checking that. I've updated the PR description and I marked that the issue is partially fixed. Can you review the PR again without taking into consideration the mentioned issue?

2021-04-26 11:40 UTC, aninde approved these changes
👍

2021-04-26 12:04 UTC, merged