The native selection won't be deselected anymore when `fragmentSelection` option is enabled
handsontable/handsontable pull request #7584
Opened 2021-02-23 15:56 UTC by wszymanski

### Context

Issue #5390 introduced big change in a way how the `CopyPaste` plugin works. However, [extra `focus`](https://github.com/handsontable/handsontable/pull/5390/files#diff-b6b6d41117204c41cc8741658c5038ab1b35a559ee272cfd17ef809bcfadded2R545) call introduced within the issue change focused element unnecessary. We should base on native selection when `fragmentSelection` option is enabled.

### How has this been tested?

I compared how Handsontable `6.0.1` and current Handsontable works for `fragmentSelection` set to `cell`, `true` and `false` values.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6083
2. #6372
3. #5810

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] My change requires a change to the documentation.

2021-02-24 08:36 UTC, budnix requested changes
The fix seems to work 👏  However, the "fragmentSelection" tests do not pass on FF (tested on 85 and 86). Can you take a look at this?

2021-02-25 15:25 UTC, wszymanski commented
> The fix seems to work 👏 However, the "fragmentSelection" tests do not pass on FF (tested on 85 and 86). Can you take a look at this?

Thanks for mindfulness. Now, tests should be unified for every supported browser.

2021-03-01 10:58 UTC, budnix commented
> Thanks for mindfulness. Now, tests should be unified for every supported browser. However, there is need for bug fix due some problem with `Internet Explorer`. Tests on that browser are passing with merged code from the #7591.

So these errors will disappear on develop branch? The tests do no pass on IE 9 through Edge.
![Zrzut ekranu 2021-03-1 o 11 53 13](https://user-images.githubusercontent.com/571316/109488003-444bf600-7a85-11eb-93ea-21ba316696d6.png)

2021-03-01 11:04 UTC, wszymanski commented
> So these errors will disappear on develop branch?

Yes. Both test are using `updatedSettings` which is bugged for mentioned browsers. After calling it, a table is redrawn improperly (has just one column in presented in the visual layer - that's why test is not passing).

2021-03-01 11:09 UTC, budnix approved these changes

2021-03-01 11:11 UTC, merged