Fix #7599
handsontable/handsontable pull request #7638
Opened 2021-03-16 14:53 UTC by MiniGab

### Context
When updating a function in the settings object after initializing the grid, the new function is not used.

This PR correct the simpleEqual method in helpers.js

This is a new PR for the closed : https://github.com/handsontable/vue-handsontable-official/pull/212

### How has this been tested?
The following demos highlight the issue and correction :

@handsontable/vue 4.1.1: https://jsfiddle.net/Lxdc950k/2/ 👍
@handonstable/vue 5.1.0 https://jsfiddle.net/541q03zp/ 👎
this version : https://jsfiddle.net/f219rvu6/ 👍
The PR also add a unit test.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/7599

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [x] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-03-22 13:05 UTC, wszymanski requested changes
Hello @MiniGab. Thanks for your effort. It works, it's tested 🙂  Good job! I've just two small suggestions related to style of coding. Could you change it?

2021-03-22 13:05 UTC, wszymanski commented on wrappers/vue/src/helpers.ts
> +    return ''+objectA === ''+objectB;
```suggestion
    return '' + objectA === '' + objectB;
```

2021-03-22 16:53 UTC, MiniGab commented
Hello @wszymanski. Thank you for the feedback. I did update the PR with your suggested changes :) !

2021-03-23 12:53 UTC, wszymanski commented
@MiniGab Can I ask you for one more favor? Please add new `7599.json` file to `.changelogs/` directory (at the root of the repository). I'm pasting file content below:

```json
{
  "title": "Adding/updating a property in settings is not used when property is a function",
  "type": "fixed",
  "issue": 7599,
  "breaking": false,
  "framework": "vue"
}
```

2021-03-23 17:25 UTC, MiniGab commented
@wszymanski Done !

2021-03-24 09:55 UTC, wszymanski approved these changes
Good job 👏 There is one more QA step, @aninde will check how code works. After her review, if everything is okey, the PR should be merged.

2021-03-31 15:29 UTC, aninde commented
@MiniGab  thank you so much for putting your work into solving this problem and thus improving the quality of Handsontable-Vue.

My tests showed that this fix does not fully correct this whole regression bug because the dataset is not updated.
You can see it on the demos and gifs.

In v4.1.0 it didn't work quite well either.
We need to internally determine if we accept this partial fix for this bug and open a new regression bug on the updated data set itself. 

v4.1.1 https://jsfiddle.net/aninde/nsad42fp/
broken v5.1.0 https://jsfiddle.net/aninde/q8uLnsv0/
this fix https://jsfiddle.net/aninde/neth42yz/

![4 1 1](https://user-images.githubusercontent.com/30186818/113170114-8e6ff500-9246-11eb-9977-7ebc3224498c.gif)

![5 1 0broken](https://user-images.githubusercontent.com/30186818/113170135-92037c00-9246-11eb-9e27-8a3c8b3f0048.gif)

![this](https://user-images.githubusercontent.com/30186818/113170144-93cd3f80-9246-11eb-8f1f-2a00148dd585.gif)

2021-04-01 11:22 UTC, aninde reviewed
@MiniGab  thank you so much for putting your work into solving this problem and thus improving the quality of Handsontable-Vue.

My tests showed that this fix does not fully correct this whole regression bug because the dataset is not updated.
You can see it on the demos and gifs.

In v4.1.0 it didn't work quite well either.
We need to internally determine if we accept this as a partial fix for this bug.

v4.1.1 https://jsfiddle.net/aninde/nsad42fp/
broken v5.1.0 https://jsfiddle.net/aninde/q8uLnsv0/
this fix https://jsfiddle.net/aninde/neth42yz/

![4 1 1](https://user-images.githubusercontent.com/30186818/113170114-8e6ff500-9246-11eb-9977-7ebc3224498c.gif)

![5 1 0broken](https://user-images.githubusercontent.com/30186818/113170135-92037c00-9246-11eb-9e27-8a3c8b3f0048.gif)

![this](https://user-images.githubusercontent.com/30186818/113170144-93cd3f80-9246-11eb-8f1f-2a00148dd585.gif)

2021-07-08 09:11 UTC, AMBudnik commented
The following pull request hasn't been merged as there are some missing improvements that @aninde previously mentioned.
I wouldn't want to ask you for more help (as you have already done a lot) @MiniGab. But I just want to know if you would be interested in making any changes to the following pull requests in the nearest future.

2021-09-20 08:52 UTC, AMBudnik commented
I think that we can close this pull request as there are no updates since July. But feel free to leave a comment and I'll reopen the following pull request.

2021-09-20 08:52 UTC, closed without merging