Improved type definition for HotColumn properties in React's wrapper
handsontable/handsontable pull request #7671
Opened 2021-03-30 15:15 UTC by swistach

### Context
In our wrapper for React, we have the `HotColumn` component, where properties are defined as `Handsontable.GridSettings`.
In most scenarios it works, except for the `data` option. This one, in `ColumnSettings`, has a completely different definition.

This PR improves properties definition by replacing `GridSettings` with `ColumnSettings`.

### How has this been tested?
A) Run `npm run in react test`
B) Use PR's build on CodeSandbox to create a React example using `HotColumn` with the `data` property as a string.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. #7612

### Affected project(s):
- [x] `@handsontable/react`

2021-03-31 14:23 UTC, nikersify submitted a review, later dismissed

2021-04-01 11:18 UTC, aninde requested changes
I tried to build @Handsontable-React build locally on this branch. It failed so I can't tests in really at this point. React tests are passing. 

The error indicates a change from this commit. 
I checked `develop` for 100% certainty, @Handsontable-React builds there without any problems.

My environment: macOS 11.2.2, node v15.8.0, npm v7.5.1. 
Reproduction:
```
rimraf ./node_modules dist package-lock.json
git pull
git checkout .
npm i
npm run build
npm run in react build
```
I tried also on clean environment:
```
npm i
npm run in react build
```

Result: 
```
src/index.tsx → ./commonjs/react-handsontable.js...
[!] (plugin rpt2) Error: /Users/ndemytruk/Desktop/w/handsontable/wrappers/react/src/hotColumn.tsx(141,36): semantic error TS2345: Argument of type 'GridSettings' is not assignable to parameter of type 'ColumnSettings'.
  Types of property 'data' are incompatible.
    Type 'any[][] | RowObject[]' is not assignable to type 'string | number | ColumnDataGetterSetterFunction'.
      Type 'any[][]' is not assignable to type 'string | number | ColumnDataGetterSetterFunction'.
        Type 'any[][]' is not assignable to type 'string'.
src/hotColumn.tsx
Error: /Users/ndemytruk/Desktop/w/handsontable/wrappers/react/src/hotColumn.tsx(141,36): semantic error TS2345: Argument of type 'GridSettings' is not assignable to parameter of type 'ColumnSettings'.
  Types of property 'data' are incompatible.
    Type 'any[][] | RowObject[]' is not assignable to type 'string | number | ColumnDataGetterSetterFunction'.
      Type 'any[][]' is not assignable to type 'string | number | ColumnDataGetterSetterFunction'.
        Type 'any[][]' is not assignable to type 'string'.
    at error (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup/dist/shared/rollup.js:5275:30)
    at throwPluginError (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup/dist/shared/rollup.js:18232:12)
    at Object.error (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup/dist/shared/rollup.js:18839:24)
    at Object.error (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup/dist/shared/rollup.js:18401:38)
    at RollupContext.error (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/Users/ndemytruk/Desktop/w/handsontable/node_modules/rollup-plugin-typescript2/src/index.ts:225:5)

npm ERR! code 1
```

![Screenshot 2021-04-01 at 12 53 23](https://user-images.githubusercontent.com/30186818/113286393-6dfa7600-92ec-11eb-83d6-9839575bf759.png)

2021-04-07 13:13 UTC, aninde approved these changes
Handsontable-React builds correctly on Windows and macOS 🥇

2021-04-08 08:57 UTC, nikersify approved these changes

2021-04-08 08:58 UTC, merged