Fixes checkboxes' state management for non-built-in elements.
handsontable/handsontable pull request #7835
Opened 2021-04-21 17:47 UTC by swistach

### Context
Our built-in checkbox renderer adds listeners for `click`, `mouseup` and `change` events. We verify if `event.target` is a checkbox element, but we don't verify if that element comes from our checkbox renderer.
This PR adds additional verification for checkboxes. We have to be sure that elements have proper data attributes, which are necessary to get coordinates.
I know we should rewrite this cell type (especially editor and renderer). Here, I want to fix only this small part to allow end developers to implement something like the "check all" feature (without workarounds).

### How has this been tested?
- two E2E tests for column and row headers,
- manually tested scenario from the related issue

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. #5934

### Affected project(s):
- [x] `handsontable`
- [x] `@handsontable/angular`
- [x] `@handsontable/react`
- [x] `@handsontable/vue`

2021-04-26 15:40 UTC, aninde requested changes
The solution is very good, I tried to break it, but I didn't succeed :)
I wondered how it will affect the use of keyboard navigation. 

I found one case that is not clear to me and maybe be a bug. 
Using <kbd>TAB</kbd> for navigation when we check the checkbox on which of both headers works differently on this PR. The result of this action is that the focus has moved outside the chart.
Is this a planned change or regression?

For clarity, I paste gifs with reproductions.
![was](https://user-images.githubusercontent.com/30186818/116110905-67c2a400-a6b6-11eb-9e20-47213ba8722f.gif)

![is](https://user-images.githubusercontent.com/30186818/116110482-04d10d00-a6b6-11eb-9125-50a7a68d6614.gif)

2021-04-27 09:08 UTC, wszymanski approved these changes
Code looks good for me, just small style changes would be nice.

2021-04-27 09:08 UTC, wszymanski commented on src/renderers/checkboxRenderer/checkboxRenderer.js
> +  if (!target.hasAttribute(ATTR_ROW) || !target.hasAttribute(ATTR_COLUMN)) {
```suggestion
  }

  if (!target.hasAttribute(ATTR_ROW) || !target.hasAttribute(ATTR_COLUMN)) {
```

2021-04-27 09:08 UTC, wszymanski commented on src/renderers/checkboxRenderer/checkboxRenderer.js
> +  if (!target.hasAttribute(ATTR_ROW) || !target.hasAttribute(ATTR_COLUMN)) {
```suggestion
  }

  if (!target.hasAttribute(ATTR_ROW) || !target.hasAttribute(ATTR_COLUMN)) {
```

2021-04-27 09:08 UTC, wszymanski commented on src/renderers/checkboxRenderer/checkboxRenderer.js
> +  if (!target.hasAttribute(ATTR_ROW) || !target.hasAttribute(ATTR_COLUMN)) {
```suggestion
  }

  if (!target.hasAttribute(ATTR_ROW) || !target.hasAttribute(ATTR_COLUMN)) {
```

2021-04-27 21:55 UTC, swistach commented
@wszymanski Thank you! I applied changes.
@aninde Thank you for that comparison. However, let's look at two things:
1) Up to v8.3.2 clicking checkbox in headers throws error _because_ 
 listeners callbacks in our renderer recognize that action as clicking on a cell - not header. In my opinion, that was incorrect behavior.
2) With changes from this PR, `<input type="checkbox" />` follow the same scenario with switching `document.activeElement` by <kbd>TAB</kbd> (incl <kbd>SHIFT</kbd> modifier) as the rest of editable UI controls. Please check the following configuration:
```
columns: [
  {
    type: 'checkbox',
    title: '<input type="checkbox"/>',
  },
  { title: '<input type="text">' },
  { title: '<input type="radio">' },
  { title: '<input type="color">' },
  { title: '<input type="date">' },
  { title: '<input type="file">' },
  { title: '<input type="password">' },
  { title: '<input type="range">' },
  { title: '<input type="reset">' },
  { title: '<input type="week">' },
  { title: '<input type="button" value="button">' },
  { title: '<button>Test</button>' },
  { title: '<select></select>' },
  { title: '<textarea></textarea>' },
  { title: '<span contenteditable="true">A</span>' },
],
```
Notice that the `<button>` element's behavior differentiates from the rest of the UI controls.


Due to your's test case, I have to modify my original opinion.
We don't have to rewrite the checkbox cell type.
We *need to redefine* our support for custom UI controls as the content of cells/headers. (cc @wojciechczerniak)

2021-04-28 06:39 UTC, wszymanski approved these changes

2021-04-28 10:55 UTC, aninde approved these changes
@swistach you convinced me :)

2021-04-29 09:25 UTC, merged