Add support for IE
handsontable/handsontable pull request #8269
Opened 2021-06-23 11:16 UTC by budnix

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-06-23 13:23 UTC, Siemienik reviewed
As I'm working on MacOS I couldn't check if it works.
@aninde Could you please check it?

2021-06-23 14:12 UTC, aninde requested changes
I managed to fire it up, but only in production, via `docs: build: no-check-links`.
Documentation is displayed on `IE 11` / Windows 10 and even on the older ones, which were already off the scope. Thank you! 

The button works, but after hover, it becomes very dark. You can see it on the emulator in the BrowserStack. Maybe we should style it? WDYT @krzysztofspilka?

<img width="528" alt="Screenshot 2021-06-23 at 16 11 11" src="https://user-images.githubusercontent.com/30186818/123112012-a9b16180-d43d-11eb-8045-2e3fdceb05e0.png">

2021-06-23 16:01 UTC, krzysztofspilka commented
@aninde sure, just not now. Let's roll it out and then fix minor issues. Please move to the backlog. Thx!

2021-06-24 07:36 UTC, aninde approved these changes

2021-06-24 07:40 UTC, merged