Improve the HoT instances handling
handsontable/handsontable pull request #8286
Opened 2021-06-24 12:43 UTC by budnix

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-06-24 17:42 UTC, aninde commented
React page has similar issue, reported here https://github.com/handsontable/handsontable/issues/8289.

2021-06-25 10:01 UTC, Siemienik requested changes
@budnix Could you type out "How has this been tested?", please?

I added to `register.js` console logs:
https://github.com/handsontable/handsontable/commit/86c7fa19b50c5abf43b629d87ec40cb5136f3900#

And it does not register instances even for Vue and Vanilla:

https://user-images.githubusercontent.com/2893099/123406631-670d9780-d5ab-11eb-8668-bb7e6f8eb0c4.mp4


https://user-images.githubusercontent.com/2893099/123407300-1b0f2280-d5ac-11eb-9256-342fb7204867.mp4

2021-06-25 10:06 UTC, budnix commented on docs/9.0/guides/integrate-with-angular/angular-setting-up-a-locale.md
> +      <hot-table [data]="dataset" [colHeaders]="true" [licenseKey]="'non-commercial-and-evaluation'">
That does not work as the name `non-commercial-and-evaluation` then is treated as a prop (that not exist).

2021-06-25 10:13 UTC, Siemienik commented on docs/9.0/guides/integrate-with-angular/angular-setting-up-a-locale.md
> +      <hot-table [data]="dataset" [colHeaders]="true" [licenseKey]="'non-commercial-and-evaluation'">
That way I remove `[]` around arg name.

In Angular, you can use args in 3 different ways:
* `[licenseKey]="expression"`
* `licenseKey="string-value"`
* `(click)="onClick($event)"`

For instance `[licenseKey]="1+1"` is same as `licenseKey="2"`

2021-06-25 10:15 UTC, budnix commented on docs/9.0/guides/integrate-with-angular/angular-setting-up-a-locale.md
> +      <hot-table [data]="dataset" [colHeaders]="true" [licenseKey]="'non-commercial-and-evaluation'">
Still for that demo this not work :)

2021-06-25 10:17 UTC, budnix commented on docs/9.0/guides/integrate-with-angular/angular-setting-up-a-locale.md
> +      <hot-table [data]="dataset" [colHeaders]="true" [licenseKey]="'non-commercial-and-evaluation'">
Ok, I see the problem ... it's about square bracket 👍

2021-06-25 10:32 UTC, budnix commented
> @budnix Could you type out "How has this been tested?", please?

Can you re-check by clearing the cache? On my side, everything works. Even with your testing methodology 86c7fa1, I see that everything is registered and then destroyed on the page leaving.

![Kapture 2021-06-25 at 12 29 17](https://user-images.githubusercontent.com/571316/123411685-02edd200-d5b1-11eb-9b61-8abcf3bce5c6.gif)

About my methodology, I overloaded the Handsontable's`destroy` method and track its callee and track the lifecycles of the framework life-cycles (for Vue `beforeDestroy` etc.).

2021-06-25 10:38 UTC, budnix commented on docs/9.0/guides/integrate-with-angular/angular-setting-up-a-locale.md
> +      <hot-table [data]="dataset" [colHeaders]="true" [licenseKey]="'non-commercial-and-evaluation'">
Fixed within https://github.com/handsontable/handsontable/pull/8286/commits/9f255453965e591f6217c5444e031bcb67cb1148

2021-06-25 11:40 UTC, Siemienik approved these changes
You are right. It works. I had cached pages which were built without `htmlContentRoot`.

I removed `./node_modules/.cache`, and for make sure I run `npm run dosc:start:no-cache`

Everything works ok 🥇

2021-06-25 11:42 UTC, merged