Improve the code highlight style
handsontable/handsontable pull request #8443
Opened 2021-07-14 08:44 UTC by budnix

### Context

The PR improves the code highlight by adding the plus sign in the highlighted line (as in the https://handsontable.com/docs/8.4.0/tutorial-internationalization.html#available-languages) and changes the background color.

Before (old docs engine):
![image](https://user-images.githubusercontent.com/571316/125591956-058a01b4-9cc8-4458-9fbd-b978999fe616.png)

Before (new docs engine):
![image](https://user-images.githubusercontent.com/571316/125592023-06b16080-cfe0-4098-8576-e3ff1bfce624.png)

After:
![image](https://user-images.githubusercontent.com/571316/125592060-cbda75bb-bd95-4bcf-893e-78468133c2fd.png)

_[skip changelog]_

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. fixes #8407
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-07-14 11:30 UTC, wszymanski approved these changes
It looks good!

2021-07-14 12:18 UTC, wojciechczerniak requested changes
I agree that it looks good, but IMO we will lose code highlighting ability if we do it this way.

Code highlighting may be very useful when writing the docs to focus the reader on the essential code fragments ie. ignoring imports, class boilerplate, showing (highlighting as name says) the method body. Without adding comments to get the reader attention `// this matters`

On the other hand, tutorials would benefit from diff's like that, making it clear that lines were added. So we may take a little longer to find the solution and keep both.

Prism.js has special ```diff tag: https://prismjs.com/test.html#language=diff&text=import%20Handsontable%20from%20'handsontable'%0A%2B%20import%20esVE%20from%20'.%2Fes-ve'%0Aimport%20enGB%20from%20'.%2Fen-gb' maybe it will be better suited for this use case? It has one caveat tho, doesn't highlight the JS code as normal JS tag does

WDYT?

2021-07-15 08:44 UTC, budnix commented
> I agree that it looks good, but IMO we will lose code highlighting ability if we do it this way.
> 
> Code highlighting may be very useful when writing the docs to focus the reader on the essential code fragments ie. ignoring imports, class boilerplate, showing (highlighting as name says) the method body. Without adding comments to get the reader attention `// this matters`

> On the other hand, tutorials would benefit from diff's like that, making it clear that lines were added. So we may take a little longer to find the solution and keep both.
> 
> Prism.js has special ```diff tag: https://prismjs.com/test.html#language=diff&text=import%20Handsontable%20from%20'handsontable'%0A%2B%20import%20esVE%20from%20'.%2Fes-ve'%0Aimport%20enGB%20from%20'.%2Fen-gb' maybe it will be better suited for this use case? It has one caveat tho, doesn't highlight the JS code as normal JS tag does
> 
> WDYT?

I think that the highlighting, in that case, does the job. This is the only place where we use it so I would leave it as it is. If we use more diff-like examples in the future, we may think about improving that. Is that sound ok to you?

2021-07-15 13:31 UTC, wojciechczerniak commented
No, not really. If we change the highlighting no one will ever use it for other purpose than diff'ing. We're taking a tool from technical writing toolset and changing it into something else.

Highlight is enough in this case and is a more universal.

2021-07-15 13:32 UTC, wojciechczerniak commented on docs/.vuepress/theme/styles/code-group.styl
> +div[class*="language-"] .highlight-lines {
Is there a way to add custom class to example block? 

```suggestion
div[class*="language-"] .highlight-lines.highlight-diff {
```

Usage
```
```example { highlight={2,4} class=.highlight-diff }

```

2021-08-03 11:06 UTC, budnix commented
> No, not really. If we change the highlighting no one will ever use it for other purpose than diff'ing. We're taking a tool from technical writing toolset and changing it into something else.
> 
> Highlight is enough in this case and is a more universal.

It's not easy to implement a new syntax for diffing like `js { highlight={2,4} class=.highlight-diff }`. I haven't found any interesting plugin for markdown-it. 

At this point, I don't know what to do with the task. The PR is about improving the highlighting syntax, so I restored the original look based on the older engine. I suggest closing the PR or accept the with the changes in styles and then create a separate issue with "diff" ideas WDYT?

2021-08-04 13:10 UTC, budnix commented
After discussion with @wojciechczerniak, we both agreed that we want to leave the original Vuepress highlight color.

2021-08-04 13:10 UTC, closed without merging