Fix overlapping HoT root element in demos
handsontable/handsontable pull request #8449
Opened 2021-07-14 11:12 UTC by budnix

### Context

The PR fixes all demos that overlap the parent element. 

_[skip changelog]_

### How has this been tested?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. fixes #8274
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-07-14 12:24 UTC, wszymanski approved these changes

2021-07-19 15:09 UTC, aninde requested changes
In addition to those unfixable, mentioned in the PR description, there are also remaining ones to be repaired: 
https://handsontable.com/docs/binding-to-data/#array-of-arrays-with-a-selective-display-of-columns
https://handsontable.com/docs/setting-options/#single-column
https://handsontable.com/docs/setting-options/#show-time
https://handsontable.com/docs/vue-hot-column/#declaring-column-settings
https://handsontable.com/docs/vue-hot-column/#array-of-objects
https://handsontable.com/docs/cell-renderer/#rendering-custom-html-in-cells
https://handsontable.com/docs/vue-hot-column/#declaring-a-custom-editor-as-a-component

2021-08-03 10:05 UTC, budnix commented
> In addition to those unfixable, mentioned in the PR description, there are also remaining ones to be repaired:
> https://handsontable.com/docs/binding-to-data/#array-of-arrays-with-a-selective-display-of-columns
> https://handsontable.com/docs/setting-options/#single-column
> https://handsontable.com/docs/setting-options/#show-time
> https://handsontable.com/docs/vue-hot-column/#declaring-column-settings
> https://handsontable.com/docs/vue-hot-column/#array-of-objects
> https://handsontable.com/docs/cell-renderer/#rendering-custom-html-in-cells
> https://handsontable.com/docs/vue-hot-column/#declaring-a-custom-editor-as-a-component

I've updated mentioned demos https://github.com/handsontable/handsontable/pull/8449/commits/3963bda462b2437987adef0319ad473d428ffed0.

2021-08-03 11:46 UTC, aninde approved these changes
Thanks!

2021-08-05 09:36 UTC, merged