Documentation: removed workaround what I did in jsdoc
handsontable/handsontable pull request #8496
Opened 2021-07-15 09:34 UTC by Siemienik

### Context
In the early stage of new documentation development I changed links from `{@link ClassName#methodName}` to `{@link class-name#methodname ClassName#methodName}`. Now I revert these changes and adjust the converter to deal with that.

Additionally, I found 3 links created by markdown syntax, and I changed it to the jsdoc syntax.

### How has this been tested?
1. `npm run docs:api` - regenerates API references
2. `npm run docs:build` - builds website and then runs link checker.
3. expected result:
```
XLSX report saved into /Users/siemienik/WebstormProjects/handsontable/docs/report-check-links.xlsx

CHECK FOR BROKEN LINKS FINISHED
Checked internals : 656
Checked externals : 113

NO BROKEN LINKS DETECTED!
```
4. then additionally I manually review all changes in generated files. To do it:
    1.  For the `/docs/next/api` I replaced `7a894582539de717787220e398c06b1f2c58077a` to `659ab339a149a32bdd86eea5b599b7eb50c49555` - what reduces diff number
    2. For the `/docs/next/api` I replaced `/next/` to `/9.0/` - what additionally reduces diff number 
    3. Compare `/docs/next/api` and `/docs/9.0/api`
    4. All links were perfect.
    5. `git reset --hard head` to clean up changes
    
### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. https://github.com/handsontable/handsontable/pull/7626#discussion_r658556225
2. https://github.com/handsontable/handsontable/pull/7626#discussion_r658558208
3.

### Affected project(s):
- Documentation

### Checklist:

- I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
-I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

2021-07-15 11:13 UTC, wojciechczerniak approved these changes
That's what I had in mind 👍

2021-07-15 11:31 UTC, budnix requested changes
It looks good. I think that you missed some links within the source code. Here the list:
 * Core:
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/core.js#L4112
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/core.js#L4125
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/core.js#L4149
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/core.js#L4161
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/core.js#L4167
 * PluginHooks
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/pluginHooks.js#L1377
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/pluginHooks.js#L1378
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/pluginHooks.js#L1388
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/pluginHooks.js#L1389
   * and ~20 occurrences more ... 
 * `plugins/autoRowSize/autoRowSize.js`
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/autoRowSize/autoRowSize.js#L47
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/autoRowSize/autoRowSize.js#L159
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/autoRowSize/autoRowSize.js#L160
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/autoRowSize/autoRowSize.js#L248
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/autoRowSize/autoRowSize.js#L249
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/autoRowSize/autoRowSize.js#L340
 * `plugins/exportFile/exportFile.js`
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/exportFile/exportFile.js#L58
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/exportFile/exportFile.js#L59
 * `plugins/manualColumnMove/manualColumnMove.js`
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/manualColumnMove/manualColumnMove.js#L28
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/manualColumnMove/manualColumnMove.js#L101
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/manualColumnMove/manualColumnMove.js#L102
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/manualColumnMove/manualColumnMove.js#L135
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/manualColumnMove/manualColumnMove.js#L358
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/manualColumnMove/manualColumnMove.js#L368
   * (the same for `manualColumnResize`, `manualRowMove`)
 * `plugins/search/search.js`
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/plugins/search/search.js#L92
 * `translations/indexMapper.js`
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L30
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L36
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L59
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L461
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L480
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L491
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L509
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L586
   * https://github.com/handsontable/handsontable/blob/feature/revert-jdsoc-workaround/src/translations/indexMapper.js#L596

2021-08-03 08:58 UTC, budnix submitted a review, later dismissed

2021-08-03 09:25 UTC, wojciechczerniak submitted a review, later dismissed

2021-08-04 11:18 UTC, budnix approved these changes

2021-08-04 11:19 UTC, wojciechczerniak approved these changes

2021-08-04 13:42 UTC, merged