Documentation: adjustment for sourceCodeLink
handsontable/handsontable pull request #8499
Opened 2021-07-15 12:41 UTC by Siemienik

### Context
I did small refactoring, sourceCodeLink was moved into the directory with a small description in the Readme.

### How has this been tested?
* `npm run docs:api` - generates proper output
* then `npm run docs:start` - serve documentation with proper links.
* 
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. #8424 
2.
3.

### Affected project(s):
-  Documentation

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

2021-07-15 12:48 UTC, budnix approved these changes

2021-07-15 13:49 UTC, wszymanski requested changes
Just small improvements suggestion.

2021-07-15 13:49 UTC, wszymanski commented on docs/.vuepress/containers/sourceCodeLink/README.md
> +4. Then vue loader handles the template and the OutboundLink within (a Vue component).
```suggestion
3. Then during `npm run docs:build` or `npm run docs:start` the markdown loader recognizes this container and outputs the Vue template.
4. Then Vue loader handles the template and the OutboundLink within (a Vue component).
```

2021-07-15 13:56 UTC, wszymanski approved these changes

2021-07-15 14:05 UTC, budnix approved these changes

2021-07-16 07:34 UTC, aninde approved these changes
👍

2021-07-20 11:27 UTC, merged