Documentation of Comments plugin configuration is more specific [skip ci] #8416
handsontable/handsontable pull request #8515
Opened 2021-07-16 09:36 UTC by wszymanski

### Context

Just minor improvement in the plugin configuration.

[skip changelog]

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8416 

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] My change requires a change to the documentation.

2021-07-16 09:45 UTC, Siemienik approved these changes

2021-07-16 09:46 UTC, Siemienik reviewed
Could you additionally update the API Ref for the `9.0` version?

2021-07-16 10:28 UTC, wszymanski commented
> Could you additionally update the API Ref for the `9.0` version?

Done.

2021-07-16 11:26 UTC, kirszenbaum requested changes

2021-07-16 11:26 UTC, kirszenbaum commented on docs/9.0/guides/cell-features/comments.md
> +## Set width and height for comment
```suggestion
## Set a comment box's size
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/9.0/guides/cell-features/comments.md
> +You can use constant dimensions for comment box using `style` parameter.
```suggestion
To set the width and height of a comment box, use the `style` parameter.
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/9.0/guides/cell-features/comments.md
> +    { row: 2, col: 2, comment: { value: 'Comment 200x50 px', style: { width: 200, height: 50 } } }
```suggestion
    { row: 1, col: 1, comment: { value: 'Some comment' } },
    // add the `style` parameter
    { row: 2, col: 2, comment: { value: 'Comment 200x50 px', style: { width: 200, height: 50 } } }
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/9.0/guides/cell-features/comments.md
> +    displayDelay: 100,
```suggestion
  contextMenu: true,
  comments: { 
    // on mouseover, wait 2 seconds before the comment box displays
    displayDelay: 2000,
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/9.0/guides/cell-features/comments.md
> +## Configure display delay
```suggestion
## Set a delay for displaying comments
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/9.0/guides/cell-features/comments.md
> +It's also possible to set how many time it will take to show a comment. Just use `displayDelay` parameter.
```suggestion
To display comments after a pre-configured time delay, use the `displayDelay` parameter.
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/next/guides/cell-features/comments.md
> +## Set width and height for comment
```suggestion
## Set a comment box's size
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/next/guides/cell-features/comments.md
> +You can use constant dimensions for comment box using `style` parameter.
```suggestion
To set the width and height of a comment box, use the `style` parameter.
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/next/guides/cell-features/comments.md
> +    { row: 2, col: 2, comment: { value: 'Comment 200x50 px', style: { width: 200, height: 50 } } }
```suggestion
    { row: 1, col: 1, comment: { value: 'Some comment' } },
    // add the `style` parameter
    { row: 2, col: 2, comment: { value: 'Comment 200x50 px', style: { width: 200, height: 50 } } }
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/next/guides/cell-features/comments.md
> +## Configure display delay
```suggestion
## Set a delay for displaying comments
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/next/guides/cell-features/comments.md
> +It's also possible to set how many time it will take to show a comment. Just use `displayDelay` parameter.
```suggestion
To display comments after a pre-configured time delay, use the `displayDelay` parameter.
```

2021-07-16 11:26 UTC, kirszenbaum commented on docs/next/guides/cell-features/comments.md
> +    displayDelay: 100,
```suggestion
  contextMenu: true,
  comments: { 
    // on mouseover, wait 2 seconds before the comment box displays
    displayDelay: 2000,
```

2021-07-16 11:31 UTC, aninde approved these changes
Cool examples, they will make it easier for users for sure. In 5b402b851f2f4490da6be4eb312de4c4933015c5, I increased the delay a little so that the demo would do better. I think I should suggest changes instead of committing them right away. Should I withdraw them or can it stay that way?

2021-07-16 11:34 UTC, wszymanski commented
> Cool examples, they will make it easier for users for sure. In [5b402b8](https://github.com/handsontable/handsontable/commit/5b402b851f2f4490da6be4eb312de4c4933015c5), I increased the delay a little so that the demo would do better. I think I should suggest changes instead of committing them right away. Should I withdraw them or can it stay that way?

Please do not commit to branch and revert it. Then I will apply similar suggestion done by @kirszenbaum .

2021-07-16 13:11 UTC, kirszenbaum approved these changes

2021-07-16 13:40 UTC, aninde approved these changes
👏

2021-07-22 12:43 UTC, swistach approved these changes
LGTM 👏 

PS. Sorry for the delay 🕙 👀

2021-09-21 10:40 UTC, merged