Docs: Editing the Column Summary topic (#8535)
handsontable/handsontable pull request #8597
Opened 2021-07-28 14:37 UTC by kirszenbaum

This pull request addresses items mentioned in #8538 and #8535 (in fact, #8538 was a duplicate of one item in #8535).

I also fixed some minor grammar stuff, and rewrote a few sentences to reduce ambiguity, but I but refrained form any major rewriting for now.

Re: adding an empty row to display `columnSummary` results: this seems to have already been addressed by adding the `reversedRowCoords` option, but I added the option described in #8538 anyway, as an alternative. Let me know if you think it makes sense.

Re: `forceNumeric`: to list the exact rules of how values are forced, I'd need some additional input from th DevTeam. But in the source code, I found [this](https://github.com/handsontable/handsontable/blob/master/src/plugins/columnSummary/columnSummary.js#L352-L358), which suggests that `forceNumeric` uses [parseFloat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat). I've added this info, as I think it's useful - let me know what you think.

[skip changelog]

2021-07-29 14:09 UTC, swistach requested changes
What do you think about adding some links to the API (for options, methods or a plugin)?

2021-07-29 14:09 UTC, swistach commented on docs/next/guides/columns/column-summary.md
> +By default, the `columnSummary` plugin makes calculations on data from all rows in the endpoint's destination column. However, you can specify it differently by column and row.
```suggestion
By default, the `ColumnSummary` plugin makes calculations on data from all rows in the endpoint's destination column. However, you can specify it differently by column and row.
```

2021-07-30 08:11 UTC, kirszenbaum commented
> What do you think about adding some links to the API (for options, methods or a plugin)?

@swistach - definitely. In general, I think every parameter/option/method/plugin etc. should be a link to the API ref. But I'll create a separate issue to rewrite and restructure the whole Column Summary topic (we'll agree on the content plan beforehand), and we'll add links there

2021-07-30 18:28 UTC, swistach approved these changes
LGTM :+1:

2021-08-03 10:13 UTC, aninde approved these changes
Thanks awfully!

2021-08-05 08:34 UTC, merged