Improved `selectOptions` documentation and typescript definition
handsontable/handsontable pull request #8647
Opened 2021-08-17 11:20 UTC by swistach

### Context
Accordingly to the reported mismatch (#8488) between what that option is doing and how we described it in our documentation - I improved JSDocs and d.ts file to cover supported use cases.

Additionally, this PR contains new tests for TS definition and missing the E2E test for using `selectOptions` as a function.

### How has this been tested?
Used each supported type for `selectOptions` option.
- `string[]`
- `{ [prop: string]: string }`
- `(visualRow: number, visualColumn: number, prop: string | number) => string[] | { [prop: string]: string }`

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. #8488 

### Affected project(s):
- [x] `handsontable`

2021-08-18 09:49 UTC, wszymanski submitted a review, later dismissed
LGFM 🎉

2021-08-18 14:28 UTC, kirszenbaum requested changes

2021-08-18 14:28 UTC, kirszenbaum commented on .changelogs/8488.json
> +  "title": "Improved documentation and TypeScript definition for 'selectOptions' option.",
```suggestion
  "title": "Improved the documentation and TypeScript definition of the `selectOptions` option.",
```

2021-08-18 14:28 UTC, kirszenbaum commented on src/dataMap/metaManager/metaSchema.js
> +     *     // as an array of strings, `option.value` and `option.textContent` uses the same value
```suggestion
     *     // as an array of strings: `option.value` and `option.textContent` use the same value
```

2021-08-18 14:28 UTC, kirszenbaum commented on src/dataMap/metaManager/metaSchema.js
> +     *     // as an object - `option.value` points a key, `option.textContent` contains string assigned to the key
```suggestion
     *     // as an object: `option.value` appoints a key, and `option.textContent` contains a string assigned to the key
```
```suggestion
     *     // as an object - `option.value` points a key, `option.textContent` contains string assigned to the key
```

2021-08-18 14:28 UTC, kirszenbaum commented on src/dataMap/metaManager/metaSchema.js
> +     *     // as a function returning possible options as an array
```suggestion
     *     // as a function that returns possible options as an array
```

2021-08-18 14:28 UTC, kirszenbaum commented on src/dataMap/metaManager/metaSchema.js
> +     *     // as a function returning possible options as an object
```suggestion
     *     // as a function that returns possible options as an object
```

2021-08-19 08:10 UTC, wszymanski approved these changes

2021-08-19 09:28 UTC, kirszenbaum approved these changes

2021-08-19 15:27 UTC, merged