Change default values for `autoWrap{Row,Col}` options
handsontable/handsontable pull request #8675
Opened 2021-08-25 08:07 UTC by budnix

### Context

The PR changes the default values for the `autoWrapRow` and `autoWrapCol` options. By default the auto wrap is disabled.

### How has this been tested?

The tests that check the selection are adjusted.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. fixes #8662
2.
3.

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2021-09-01 14:00 UTC, kirszenbaum requested changes
@budnix - I made a separate PR to update the docs: https://github.com/handsontable/handsontable/pull/8686

2021-09-01 14:28 UTC, wszymanski submitted a review, later dismissed

2021-09-01 15:04 UTC, kirszenbaum approved these changes

2021-09-10 09:45 UTC, budnix commented
@wszymanski 🏓

2021-09-10 09:51 UTC, wszymanski approved these changes

2021-09-10 09:54 UTC, merged