Docs: Row hiding
handsontable/handsontable pull request #8692
Opened 2021-09-02 12:48 UTC by kirszenbaum

This PR:
- Fixes #7390 
- Fixes #8474 
- Rewrites the [Row hiding](https://handsontable.com/docs/row-hiding/) topic
- Polishes tthe [Column hiding]https://handsontable.com/docs/column-hiding/) topic, to ensure consistency

2021-09-06 16:34 UTC, swistach requested changes
What do you think about omitting instances' references when we describe process/action using methods names?
Of course, an instance's reference is necessary for the code block.

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
> +  data: Handsontable.helper.createSpreadsheetData(12,5),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(12, 5),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
> +  data: Handsontable.helper.createSpreadsheetData(12,5),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(12, 5),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
> +  data: Handsontable.helper.createSpreadsheetData(12,5),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(12, 5),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
>    data: Handsontable.helper.createSpreadsheetData(12,5),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(12, 5),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
> +  data: Handsontable.helper.createSpreadsheetData(12,5),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(12, 5),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
> +  data: Handsontable.helper.createSpreadsheetData(12,5),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(12, 5),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/rows/row-hiding.md
> +To see your changes, re-render your Handsontable instance with the [`hot.render()`](@/api/core.md#render) method.
```suggestion
To see your changes, re-render your Handsontable instance with the [`render()`](@/api/core.md#render) method.
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/columns/column-hiding.md
>    data: Handsontable.helper.createSpreadsheetData(5,12),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(5, 12),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/columns/column-hiding.md
>    data: Handsontable.helper.createSpreadsheetData(5,12),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(5, 12),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/columns/column-hiding.md
>    data: Handsontable.helper.createSpreadsheetData(5,12),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(5, 12),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/columns/column-hiding.md
>    data: Handsontable.helper.createSpreadsheetData(5,12),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(5, 12),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/columns/column-hiding.md
>    data: Handsontable.helper.createSpreadsheetData(5,12),
```suggestion
  data: Handsontable.helper.createSpreadsheetData(5, 12),
```

2021-09-06 16:34 UTC, swistach commented on docs/next/guides/columns/column-hiding.md
> +To see your changes, re-render your Handsontable instance with the [`hot.render()`](@/api/core.md#render) method.
```suggestion
To see your changes, re-render your Handsontable instance with the [`render()`](@/api/core.md#render) method.
```

2021-09-13 09:01 UTC, kirszenbaum commented
> What do you think about omitting instances' references when we describe process/action using methods names?
> Of course, an instance's reference is necessary for the code block.

You mean e.g. `render()` rather than `hot.render()`? Yeah, definitely!

2021-09-15 08:00 UTC, mrpiotr-dev approved these changes
LGTM 👍

2021-09-15 08:42 UTC, merged