Add `registerAll*` functions to the Base module
handsontable/handsontable pull request #8846
Opened 2021-10-06 13:25 UTC by budnix

### Context

The PR is a base branch for support for modularized wrappers.

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2021-10-12 20:19 UTC, budnix commented
> Code looks great 🏆
> 
> But I think that `/docs` are missing for all new exports. We should describe them on our modules page, right?

Right! As you accepted the changes, the API becomes stable so with help @kirszenbaum we can start working on docs.

2021-10-26 10:56 UTC, wojciechczerniak submitted a review, later dismissed
I see docs are being worked on within #8892. No need to block this PR then

2021-11-03 10:53 UTC, kirszenbaum requested changes

2021-11-03 10:53 UTC, kirszenbaum commented on .changelogs/8819.json
> +  "title": "Added support for modularize React wrapper",
```suggestion
  "title": "Added support for the modularized React wrapper.",
```

2021-11-03 10:53 UTC, kirszenbaum commented on .changelogs/8820.json
> +  "title": "Added support for modularize Vue wrapper",
```suggestion
  "title": "Added support for the modularized Vue wrapper.",
```

2021-11-04 09:02 UTC, merged