[RTL] Fixed issues with numeric and time formatting in RTL mode.
handsontable/handsontable pull request #8906
Opened 2021-10-27 11:17 UTC by Siemienik

### Context
Based on https://github.com/handsontable/handsontable/pull/8893 ([diff](https://github.com/handsontable/handsontable/compare/feature/issue-8795...feature/issue-8791))

Fixed issues with numeric and time formatting in RTL mode. Setting `dir=ltr` forces to display the correct value as formatted in settings. For another format, it should be achieved by format on the settings level.

Resolves: #8805 #8791

### How has this been tested?

I used configurations from the issues. Then I checked for both LTR and RTL mode. Additionally, I update the test suits to cover these changes.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. Resolves: #8805 
2. Resolves: #8791
3. Part of #8760 

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

2021-11-08 13:26 UTC, wszymanski approved these changes

2021-11-08 13:30 UTC, wszymanski commented
I'm sorry, I've accepted this PR by mistake. I'll review it soon.

2021-11-08 13:30 UTC, wszymanski submitted a review, later dismissed
I'm sorry, I've accepted this PR by mistake. I'll review it soon.

2021-12-07 08:39 UTC, budnix requested changes
I left my suggestions in the comments.

2021-12-07 08:41 UTC, budnix commented on handsontable/src/renderers/textRenderer/textRenderer.js
> +  if (cellProperties.type === 'time') {
The same case is mentioned here https://github.com/handsontable/handsontable/pull/8906#discussion_r763077563

2021-12-07 10:18 UTC, budnix commented on handsontable/src/renderers/numericRenderer/numericRenderer.js
> +    TD.dir = 'ltr';
The TD elements that are injected by Walkontable are reused during the HoT usage. To make sure that the TD attributes do not go over to another cell (after CRUD operations, hiding columns/rows, etc) the TD attribute has to be cleared.

May I suggest updating [the line of code](https://github.com/handsontable/handsontable/blob/feature/issue-8791/handsontable/src/3rdparty/walkontable/src/renderer/cells.js#L92) and add `TD.removeAttribute('dir');`?

2021-12-21 08:18 UTC, budnix commented on handsontable/src/renderers/numericRenderer/numericRenderer.js
> +    TD.dir = 'ltr';
Resolved within 92a351e

2021-12-21 09:00 UTC, budnix commented
I finished working on this PR. I implemented all of the ideas and suggestions that I had while reviewing the code. If @Siemienik approves the changes the PR can be merged. Things that I pushed:
 * Removed `dir` attribute from the cell element within Walkontable's cells renderer (92a351ef79566a6fd2aa5bcfbd0cb6ea7a881958) and cover the changes with the test (361699ffd8fc884efbba236a4f3be285ae80e1f5);
 * Following the separation of concern I removed the `time` logic that was originally placed within the TextEditor and text renderer I create new TimeEditor and time renderer with a proper RTL changes (ce7a709ca78d6cf001148f4eb9bfb509d3819e8a, 12def75447482ca6e21f87532930f95d27935d75).
 * Added the RTL tests for all editors and renderers to make sure that the "dir" attribute change within other editors and renderers will be caught.

2021-12-27 14:04 UTC, Siemienik commented
Thank you @budnix for your improvements, It looks good to me 🥇. IMHO, we may merge this.

2021-12-27 20:58 UTC, budnix approved these changes

2021-12-27 21:07 UTC, merged