Docs: Moving the React "Using the HotColumn component" examples from CodeSandbox to the HoT docs
handsontable/handsontable pull request #8966
Opened 2021-11-23 10:57 UTC by kirszenbaum

This PR continues #8962 :
- Moves the React examples from the [Using the HotColumn component](https://handsontable.com/docs/react-hot-column/) page from CodeSandbox to the Handsontable docs

### Declaring column settings (done in #8962 )
- Old CodeSandbox example: https://codesandbox.io/embed/declaring-column-settings-seg0l?fontsize=14&theme=dark
- New docs example: http://localhost:8080/docs/next/react-hot-column/#declaring-column-settings
- Seems to be working fine

### Declaring a custom renderer as a component (done in #8962 )
- Old CodeSandbox example: https://codesandbox.io/embed/declaring-a-custom-renderer-as-a-component-4yv9m?fontsize=14&theme=dark
- New docs example: http://localhost:8080/docs/next/react-hot-column/#declaring-a-custom-renderer-as-a-component
- Seems to be working fine, but:
  - I had to "merge" the separate `rendererComponent.jsx` file into the main code snippet

### Object data source
- Old CodeSandbox example: https://codesandbox.io/embed/object-data-source-y8xwr?fontsize=14&theme=dark
- New docs example: http://localhost:8080/docs/next/react-hot-column/#object-data-source

### Declaring a custom editor as a component
- Old CodeSandbox example: https://codesandbox.io/embed/declaring-a-custom-editor-as-a-component-qhbnv?fontsize=14&theme=dark
- New docs example: http://localhost:8080/docs/next/react-hot-column/#declaring-a-custom-editor-as-a-component

### Using the renderer/editor components with React's Context
- Old CodeSandbox example: https://codesandbox.io/embed/using-the-renderer-component-with-reacts-context-forked-27pl0?fontsize=14&theme=dark
- New docs example: http://localhost:8080/docs/next/react-hot-column/#using-the-renderer-editor-components-with-react-s-context

### An advanced example
- Old CodeSandbox example: https://codesandbox.io/embed/advanced-handsontablereact-implementation-using-hotcolumn-forked-jgrk2?fontsize=14&theme=dark
- New docs example: http://localhost:8080/docs/next/react-hot-column/#an-advanced-example

[skip changelog]

2021-11-23 23:48 UTC, warpech requested changes
I took it as a challenge to fix the remaining snippets. Please review if works for you now. The example 6 will not work in JSFiddle unless you deploy it on our server (because it needs the current changes in `fixes.js` to be deployed.

Below is one additional suggestion.

2021-11-24 09:52 UTC, kirszenbaum commented on docs/11.0/guides/integrate-with-react/react-hot-column.md
> +    },
@warpech - done: 43f0a8e (I also fixed the order of the IDs)

2021-11-25 16:11 UTC, warpech commented on docs/11.0/guides/integrate-with-react/react-hot-column.md
> +    },
Thanks!

2021-11-25 16:12 UTC, warpech commented
I will not be able to help with the problems listed in the last comment (and probably not all are problems). 

@jansiegel can you help out?

2021-11-26 08:53 UTC, warpech submitted a review, later dismissed
I discussed with @kirszenbaum that the changes can be accepted now. The remaining problems are tracked in new issues, and can be fixed later with high priority.

2021-11-26 09:16 UTC, warpech approved these changes

2021-11-26 09:18 UTC, merged

2021-11-26 10:22 UTC, jansiegel commented
@kirszenbaum @warpech 
As for:
> In the 5th example, after clicking on the Preview tab, you're stuck: you can't click on the remaining tabs anymore

it seems to be caused by the styles of the `h1 - h3` headers. The `<h3>` header's margin rendered in this example covers the tab buttons, making them impossible to be clicked.

The problematic fragment is here: https://github.com/handsontable/handsontable/blob/develop/docs/.vuepress/theme/styles/index.styl#L139

I'd suggest changing
```
h1 {
```
to something like  this (for `h1`, `h2` and `h3`):
```
.theme-default-content > h1 {
```
if it makes sense in the current theme. 

Also, there's quite a lot of `!important`s in the styles - I'd try to get rid of those, as they'll most probably eventually cause some issues.