Add ability to create custom redirects for documentation.
handsontable/handsontable pull request #9043
Opened 2021-12-16 07:00 UTC by budnix

### Context

The PR adds the ability to create custom redirects for documentation. The rules only apply for pages that URL path starts with `/docs/`.

The change covers the following redirect rules:
| Legacy URLs               |  Current URLs                   | 
|----------------------------------------------------------------------|---------------------------------------------------------------|
| /docs/hyperformula     |  [/hyperformula](https://handsontable.github.io/hyperformula) | 
| /docs/hyperformula/whatever/whatever     |  [/hyperformula/whatever/whatever](https://handsontable.github.io/hyperformula/whatever/whatever) | 
| /docs/tutorial-introduction.html         |  /docs/                            | 
| /docs/tutorial-compatibility.html        |  /docs/supported-browsers          | 
| /docs/tutorial-licensing.html            |  /docs/software-license            | 
| /docs/tutorial-license-key.html          |  /docs/license-key                 | 
| /docs/tutorial-quick-start.html          |  /docs/installation                | 
| /docs/tutorial-data-binding.html         |  /docs/binding-to-data             | 
| /docs/tutorial-data-sources.html         |  /docs/binding-to-data             | 
| /docs/tutorial-load-and-save.html        |  /docs/saving-data                 | 
| /docs/tutorial-setting-options.html      |  /docs/setting-options             | 
| /docs/tutorial-grid-sizing.html          |  /docs/grid-size                   | 
| /docs/tutorial-using-callbacks.html      |  /docs/events-and-hooks            | 
| /docs/tutorial-keyboard-navigation.html  |  /docs/keyboard-navigation         | 
| /docs/tutorial-internationalization.html |  /docs/internationalization-i18n   | 
| /docs/tutorial-modules.html              |  /docs/modules                     | 
| /docs/tutorial-custom-build.html         |  /docs/building                    | 
| /docs/tutorial-custom-plugin.html        |  /docs/plugins                     | 
| /docs/tutorial-cell-types.html           |  /docs/cell-type                   | 
| /docs/tutorial-cell-editor.html          |  /docs/cell-editor                 | 
| /docs/tutorial-cell-function.html        |  /docs/cell-function               | 
| /docs/tutorial-suspend-rendering.html    |  /docs/batch-operations            | 
| /docs/tutorial-testing.html              |  /docs/testing                     | 
| /docs/tutorial-performance-tips.html     |  /docs/performance                 | 
| /docs/tutorial-release-notes.html        |  /docs/release-notes               | 
| /docs/tutorial-migration-guide.html      |  /docs/migration-from-7.4-to-8.0   | 
| /docs/demo-scrolling.html                |  /docs/row-virtualization          | 
| /docs/demo-fixing.html                   |  /docs/column-freezing             | 
| /docs/demo-resizing.html                 |  /docs/column-width                | 
| /docs/demo-moving.html                   |  /docs/column-moving               | 
| /docs/demo-pre-populating.html           |  /docs/row-prepopulating           | 
| /docs/demo-stretching.html               |  /docs/column-width                | 
| /docs/demo-freezing.html                 |  /docs/column-freezing             | 
| /docs/demo-fixing-bottom.html            |  /docs/row-freezing                | 
| /docs/demo-hiding-rows.html              |  /docs/row-hiding                  | 
| /docs/demo-hiding-columns.html           |  /docs/column-hiding               | 
| /docs/demo-trimming-rows.html            |  /docs/row-trimming                | 
| /docs/demo-bind-rows-headers.html        |  /docs/row-header                  | 
| /docs/demo-collapsing-columns.html       |  /docs/column-groups               | 
| /docs/demo-nested-headers.html           |  /docs/column-groups               | 
| /docs/demo-nested-rows.html              |  /docs/row-parent-child            | 
| /docs/demo-dropdown-menu.html            |  /docs/column-menu                 | 
| /docs/demo-sorting.html                  |  /docs/row-sorting                 | 
| /docs/demo-multicolumn-sorting.html      |  /docs/row-sorting                 | 
| /docs/demo-searching.html                |  /docs/searching-values            | 
| /docs/demo-filtering.html                |  /docs/column-filter               | 
| /docs/demo-summary-calculations.html     |  /docs/column-summary              | 
| /docs/demo-data-validation.html          |  /docs/cell-validator              | 
| /docs/demo-auto-fill.html                |  /docs/autofill-values             | 
| /docs/demo-merged-cells.html             |  /docs/merge-cells                 | 
| /docs/demo-alignment.html                |  /docs/text-alignment              | 
| /docs/demo-read-only.html                |  /docs/disabled-cells              | 
| /docs/demo-disabled-editing.html         |  /docs/disabled-cells              | 
| /docs/demo-custom-renderers.html         |  /docs/cell-renderer               | 
| /docs/demo-numeric.html                  |  /docs/numeric-cell-type           | 
| /docs/demo-date.html                     |  /docs/date-cell-type              | 
| /docs/demo-time.html                     |  /docs/time-cell-type              | 
| /docs/demo-checkbox.html                 |  /docs/checkbox-cell-type          | 
| /docs/demo-select.html                   |  /docs/select-cell-type            | 
| /docs/demo-dropdown.html                 |  /docs/dropdown-cell-type          | 
| /docs/demo-autocomplete.html             |  /docs/autocomplete-cell-type      | 
| /docs/demo-password.html                 |  /docs/password-cell-type          | 
| /docs/demo-handsontable.html             |  /docs/handsontable-cell-type      | 
| /docs/demo-context-menu.html             |  /docs/context-menu                | 
| /docs/demo-spreadsheet-icons.html        |  /docs/icon-pack                   | 
| /docs/demo-comments_.html                |  /docs/comments                    | 
| /docs/demo-copy-paste.html               |  /docs/basic-clipboard             | 
| /docs/demo-export-file.html              |  /docs/export-to-csv               | 
| /docs/demo-conditional-formatting.html   |  /docs/conditional-formatting      | 
| /docs/demo-customizing-borders.html      |  /docs/formatting-cells            | 
| /docs/demo-selecting-ranges.html         |  /docs/selection                   | 
| /docs/demo-formula-support.html          |  /docs/formula-calculation         | 
| /docs/react                              |  /docs/react-installation          | 
| /docs/angular                            |  /docs/angular-installation        | 
| /docs/vue3                               |  /docs/vue3-installation           | 
| /docs/vue                                |  /docs/vue-installation            | 
| /docs/i18n/missing-language-code         |  /docs/internationalization        | 
| /docs/frameworks-wrapper-for-react-simple-examples.html               |  /docs/react-simple-examples               | 
| /docs/frameworks-wrapper-for-react-...                                |  /docs/react-...                           | 
| /docs/frameworks-wrapper-for-vue-installation.html                    |  /docs/vue-installation                    | 
| /docs/frameworks-wrapper-for-vue-...                                  |  /docs/vue-...                             | 
| /docs/frameworks-wrapper-for-angular-installation.html                |  /docs/angular-installation                | 
| /docs/frameworks-wrapper-for-angular-...                              |  /docs/angular-...                         | 
| /docs/9.0/tutorial-compatibility.html                                     |  /docs/9.0/supported-browsers                  | 
| /docs/9.0/tutorial-licensing.html                                         |  /docs/9.0/software-license                    | 
| /docs/9.0/tutorial-license-key.html                                       |  /docs/9.0/license-key                         | 
| /docs/9.0/tutorial-quick-start [...]

2021-12-16 08:04 UTC, warpech commented on docs/docker/redirects.conf
> +#rewrite ^/11.0/api/temp-collection/?$ /docs/11.0/api/other-page/ permanent;
I guess that we already have some manual redirection rules. Can they be moved to here for clarity?

2021-12-16 10:07 UTC, kirszenbaum requested changes
@budnix - this looks great, thanks a lot!

2021-12-16 10:07 UTC, kirszenbaum commented on docs/docker/redirects.conf
> +#rewrite ^/11.0/api/temp-collection/?$ /docs/11.0/api/other-page/ permanent;
```suggestion
# This file lists Nginx rewrite rules for the documentation pages:
# (i.e. pages whose URL paths start with /docs/).
# 
# Usage examples:
#  - To redirect permanently (using the HTTP 301 code)
#    from https://handsontable.com/docs/api/very-old-collection
#    to https://handsontable.com/docs/api/new-collection
#    add the following, uncommented line:
#    rewrite ^/api/very-old-collection/?$ /docs/api/new-collection/ permanent;
#
#  - Redirect temporarily (using the HTTP 302 code)
#    from https://handsontable.com/docs/11.0/api/temp-collection
#    to https://handsontable.com/docs/11.0/api/other-page
#    add the following, uncommented line:
#    rewrite ^/11.0/api/temp-collection/?$ /docs/11.0/api/other-page/ permanent;
#
# Read more:
# - Creating Nginx rewrite rules: https://www.nginx.com/blog/creating-nginx-rewrite-rules/
# - The Ngix rewrite module docs: http://nginx.org/en/docs/http/ngx_http_rewrite_module.html
```

2021-12-16 10:07 UTC, kirszenbaum commented on docs/docker/redirects.conf
> +# --- frameworks shortcut ---
```suggestion
# --- framework shortcuts ---
```

2021-12-16 10:07 UTC, kirszenbaum commented on docs/docker/redirects.conf
> +# --- HoT logs that in the console ---
```suggestion
# --- documentation links in Handsontable's console logs ---
```

2021-12-16 11:10 UTC, kirszenbaum approved these changes

2021-12-16 13:36 UTC, kirszenbaum approved these changes

2021-12-21 08:17 UTC, budnix commented
@warpech 🏓

2021-12-21 11:25 UTC, warpech commented
@kirszenbaum have you tested it in the following way?

- broken links checker reports 404 on some page
- you fix that 404 by redirecting the dead link to some other page in `redirects.conf` (I am not saying this will always be the solution, but sometimes yes)
- broken links checker no longer reports the 404

2021-12-21 13:14 UTC, kirszenbaum commented
> @kirszenbaum have you tested it in the following way?
> 
> * broken links checker reports 404 on some page
> * you fix that 404 by redirecting the dead link to some other page in `redirects.conf` (I am not saying this will always be the solution, but sometimes yes)
> * broken links checker no longer reports the 404

@warpech, @budnix No, I didn't test it, just corrected the content added.

I now tried this:
1. `npm run docs:build`.
2. The broken links report shows, for example, this link:
    <img width="1088" alt="2" src="https://user-images.githubusercontent.com/29247866/146935499-1d8256c6-82f7-440b-999e-24794787d46d.png">
3. I add the following rule:
    `rewrite ^/10.0/vue3-installation/$ /docs/10.0/vue-installation/ permanent;`
4. `npm run docs:build`
5. The link is still coming up in the broken links report:
     <img width="1088" alt="2" src="https://user-images.githubusercontent.com/29247866/146935499-1d8256c6-82f7-440b-999e-24794787d46d.png">

Am I doing sth wrong?

2021-12-21 13:29 UTC, budnix commented
> 
> 1. `npm run docs:build`.
> 2. The broken links report shows, for example, this link:
>    <img alt="2" width="1088" src="https://user-images.githubusercontent.com/29247866/146935499-1d8256c6-82f7-440b-999e-24794787d46d.png">
> 3. I add the following rule:
>    `rewrite ^/10.0/vue3-installation/$ /docs/10.0/vue-installation/ permanent;`
> 4. `npm run docs:build`
> 5. The link is still coming up in the broken links report:
>    <img alt="2" width="1088" src="https://user-images.githubusercontent.com/29247866/146935499-1d8256c6-82f7-440b-999e-24794787d46d.png">
> 
> Am I doing sth wrong?

These kinds of redirects work on staging or on production only. You can try to create a separate branch with changes and deploy it manually using [Docs Staging Deployment](https://github.com/handsontable/handsontable/actions/workflows/docs-staging.yml) workflow. Within the "Run workflow" button select a newly created branch and click "Run". Another tip is that Chrome likes to cache the rewrites so if you're sure that the rule is correct but it still doesn't work try incognito mode.

2021-12-21 13:56 UTC, kirszenbaum commented
> > 1. `npm run docs:build`.
> > 2. The broken links report shows, for example, this link:
> >    <img alt="2" width="1088" src="https://user-images.githubusercontent.com/29247866/146935499-1d8256c6-82f7-440b-999e-24794787d46d.png">
> > 3. I add the following rule:
> >    `rewrite ^/10.0/vue3-installation/$ /docs/10.0/vue-installation/ permanent;`
> > 4. `npm run docs:build`
> > 5. The link is still coming up in the broken links report:
> >    <img alt="2" width="1088" src="https://user-images.githubusercontent.com/29247866/146935499-1d8256c6-82f7-440b-999e-24794787d46d.png">
> > 
> > Am I doing sth wrong?
> 
> These kinds of redirects work on staging or on production only. You can try to create a separate branch with changes and deploy it manually using [Docs Staging Deployment](https://github.com/handsontable/handsontable/actions/workflows/docs-staging.yml) workflow. Within the "Run workflow" button select a newly created branch and click "Run". Another tip is that Chrome likes to cache the rewrites so if you're sure that the rule is correct but it still doesn't work try incognito mode.

@budnix Thanks, makes sense!

I deployed the changes to Staging (from a [`feature/docs-manual-redirects-test` branch](https://github.com/handsontable/handsontable/blob/feature/docs-manual-redirects-test/docs/docker/redirects.conf#L67)), but it doesn't seem to work: https://dev.handsontable.com/docs/10.0/vue3-installation/ (should redirect to: https://dev.handsontable.com/docs/10.0/vue-installation/). Tried resetting cache and incognito

2021-12-30 12:06 UTC, warpech commented
So if I understand correctly, the broken links checker spawns its own dumb HTTP server (https://github.com/handsontable/handsontable/blob/5c392c3ec12e1684d9735ef1e20541b46ac8ff5d/docs/.vuepress/tools/check-links.js#L10) instead of using our Docker image. If we managed to run the Docker image locally, the broken links checker could use that instead, including all of the redirections.

@budnix do you confirm?

Anyway, that appears to be out of scope here. @kirszenbaum if you agree that this is worth pursuing, please make a new issue about that and add a label "Tools".

2021-12-30 12:07 UTC, warpech approved these changes
Approving the idea, I did not test

2021-12-31 06:58 UTC, merged

2021-12-31 07:17 UTC, budnix commented
> So if I understand correctly, the broken links checker spawns its own dumb HTTP server 
instead of using our Docker image. If we managed to run the Docker image locally, the broken links checker could use that instead, including all of the redirections.
> @budnix do you confirm?

True, The tool checks the local VuePress instance without checking the internal Nginx redirects. 

Once I've merged the PR I thought that it's maybe a good time o rethink how we define the redirects? The Nginx redirects are implemented to handle URLs from the previous documentation engine and mostly for handling current numbered URLs to non-numbered (`/11.0/foo` -> `/foo`). This approach allows us to redirect users in the most performant way, as fast as possible. However, there is a second alternative. We can define a list of rewrites in the VuePress conf file like:
```js
export default ({ router }) => {
  router.addRoutes([
    { path: '/foo/', redirect: '/' },
    { path: '/bar/', redirect: '/' }
  ])
}
```
it's more secure than messing with Nginx configuration (low level) but less performant.

2022-01-26 15:11 UTC, warpech commented
If I understand correctly, routes added via `addRoutes` work on the client so (among other problems) they cannot change the HTTP status code. I think that is not a valid replacement for Nginx, then.

If the only problem that we have with Nginx is that we are afraid messing with its config files, I hope that it is largely mitigated by our broken links checker.