[RTL] Fixations for ManualColumnResize plugin
handsontable/handsontable pull request #9120
Opened 2022-01-17 20:10 UTC by Siemienik

fixes for RTL mode:
* indicator position
* calculating new column size

TODO:
* [ ] check manualRowResize.js for RTL (changes there)
* [ ] add test for rtl mode

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2022-01-18 09:13 UTC, budnix requested changes
Well done :) However, I found cases where the resizing does not work.

 * The resize handler disappears when I scroll the table horizontally
![Kapture 2022-01-18 at 10 06 10](https://user-images.githubusercontent.com/571316/149905494-4ce84b20-d25b-4e71-be3f-118141eae737.gif)

 * The ruler of the handler is placed in the wrong position. It should be placed at the end of the handler.
 LTR mode
![image](https://user-images.githubusercontent.com/571316/149906360-494a9b79-5a78-4019-b4d6-854533f893c0.png)
RTL mode
![image](https://user-images.githubusercontent.com/571316/149906519-ef52ab76-e531-4d76-9ed2-5f62980d48f7.png)

2022-01-26 11:52 UTC, Siemienik commented
@budnix I fix this PR, during rereview please keep in mind that the #9134 was reviewed and merged to this PR.

2022-01-26 12:38 UTC, budnix requested changes
I've accidentally found a bug where the handlers are not correctly positioned. It happens when Handsontable is initialized without defining sizing (window is a scrollable element) and on the right overlay.

![Kapture 2022-01-26 at 13 38 24](https://user-images.githubusercontent.com/571316/151164355-816fc36f-9d1f-4bab-af19-138a2fb7063c.gif)

2022-01-26 12:38 UTC, budnix commented on handsontable/src/3rdparty/walkontable/src/overlay/_base.js
> +   * @returns {number|number|number|*}
```suggestion
   * @returns {number}
```

2022-01-26 20:02 UTC, Siemienik commented
@budnix would you mind providing me source code to reproduce that?

2022-01-27 08:28 UTC, budnix commented
> @budnix would you mind providing me source code to reproduce that?

Sure! https://codesandbox.io/s/vanilla-handsontable-pr-forked-tmvln?file=/src/index.js. If you scroll the page horizontally a little bit the resize handlers do not appear.

2022-02-04 15:14 UTC, jansiegel approved these changes
lgtm 👍

2022-02-09 08:27 UTC, jansiegel approved these changes

2022-02-09 08:28 UTC, merged