Filter cells with formulas using values not source (#5455)
handsontable/handsontable pull request #9159
Opened 2022-01-27 15:44 UTC by mjastrzebowski

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2022-01-28 13:20 UTC, aninde commented
I propose to add a few test cases to check relative and absolute formulas. 
For example such as:
 ```
 var data = [
       ['=SUM(B1:B2)', 1, "= A$1"],
       ['=$B1', 2, '=SUM (A1:A2)'],
   ];

...

// should filter cell with relative formula in the first cell
const filtersPlugin = hot1.getPlugin ('filters');
filtersPlugin.addCondition (0, 'by_value', ['3']);
filtersPlugin.filter()

expect (getData()[0][0]).toBe(3)

// should filter cell with absolute formula
filtersPlugin.addCondition(2, 'by_value', ['1']);
filtersPlugin.filter()

expect (getData()[0][0]).toBe(3)
```

2022-01-31 09:48 UTC, budnix requested changes
Thanks for your contribution! I've played with the changes locally using all build-in cell types and I haven't found any issues. As I played with a demo, I'm sure now that the PR is not a breaking change.

About the code, I found some nitpicky changes to consider.

2022-01-31 09:48 UTC, budnix commented on handsontable/src/plugins/filters/filters.js
> +      const dataValue = this.hot.getDataAtCell((this.hot.toVisualRow(rowIndex)), visualColumn) || value;
```suggestion
      const dataValue = this.hot.getDataAtCell(this.hot.toVisualRow(rowIndex), visualColumn) ?? value;
```
The nullish coalescing operator is a better approach here. Without that if the formula returned `0` the source value (formula expression) would be returned, thus the filter condition like `eq` with `0` would not work.

2022-01-31 10:39 UTC, mjastrzebowski commented
> filtersPlugin.addCondition(0, 'by_value', ['3']);

Added more tests for text fields as suggested by @aninde FYI `by_value` filter args should be array of values to check, so in this case: `filtersPlugin.addCondition(0, 'by_value', [['3']]);`

@budnix thanks for the review, all changes applied

2022-01-31 10:42 UTC, budnix submitted a review, later dismissed
Thanks! 👍

2022-01-31 10:50 UTC, mjastrzebowski commented
@budnix rebased with master, ready to merge

2022-01-31 10:52 UTC, budnix submitted a review, later dismissed

2022-01-31 10:59 UTC, budnix submitted a review, later dismissed

2022-02-01 08:26 UTC, budnix approved these changes

2022-02-01 08:58 UTC, merged