Add Arabic language file
handsontable/handsontable pull request #9208
Opened 2022-02-09 15:13 UTC by alshakero

### Context
This adds Arabic translation file for the UI and documents it.

### How has this been tested?
I modified the `js/demo` app to test this. This change is still in this PR just to help you test, I can revert it once the UI is tested.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8760 
2. #9150 

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2022-02-09 15:15 UTC, alshakero commented on examples/next/docs/js/demo/src/index.js
> +Handsontable.languages.registerLanguageDictionary(ar);
This change is temporary to help test the PR.

2022-02-09 15:15 UTC, alshakero commented on handsontable/src/i18n/languages/ar.js
> +  languageDirection: 'rtl',
This doesn't do anything as of now.

2022-02-10 13:46 UTC, AMBudnik commented
I'm more than glad to finally see Arabic on the list. Thank you for the contribution.

2022-02-11 08:29 UTC, budnix requested changes
Thanks for the contribution 👏  Can I ask you to change the base branch to `rtl` (not `rtl-docs`)?

2022-02-11 08:29 UTC, budnix commented on handsontable/src/i18n/languages/ar.js
> +  languageCode: 'ar',
```suggestion
  languageCode: 'ar-AR',
```
In reference to the best practices for language tags ([BCP 47](https://www.rfc-editor.org/rfc/rfc5646.html)), may we agree to use the `ar-AR` tag here?

2022-02-11 08:29 UTC, budnix commented on handsontable/src/i18n/languages/index.js
> +import ar from './ar';
```suggestion
import arAR from './ar-AR';
```

2022-02-11 08:29 UTC, budnix commented on handsontable/src/i18n/languages/index.js
> +  ar
```suggestion
  arAR
```

2022-02-11 08:29 UTC, budnix commented on docs/next/guides/internationalization/language.md
> +* `ar.js` for **Arabic - Global** (`ar` code).
```suggestion
* `ar-AR.js` for **Arabic - Global** (`ar-AR` code).
```

2022-02-11 08:29 UTC, budnix commented on examples/next/docs/js/demo/src/index.js
>  import { data } from "./constants";
Can I ask you to revert that file? AFAIK the "demo" from the examples project is currently reserved for LTR. Probably something will be changed but only after the official RTL support release.

2022-02-11 16:52 UTC, alshakero commented
Alright, I addressed all feedback and move documentation to [another PR](https://github.com/handsontable/handsontable/pull/9213) here.

2022-02-15 07:47 UTC, merged

2022-04-28 13:08 UTC, AMBudnik commented
Thank you for all your feedback, @alshakero 
v12.0 with your changes is live!