Restore the native keyboard shortcuts in cells editors
handsontable/handsontable pull request #9393
Opened 2022-04-14 10:30 UTC by budnix

### Context

The PR changes the behavior of the Home/End, Ctrl/Cmd + Z/Y keyboard shortcuts. Now it works as follows:

Shortcut | Expected behavior
-- | --
Home | Move the cursor to the beginning of the text 
End | Move the cursor to the end of the text 
Cmd/Ctrl + Z | Undo last action entered into cell's editor 
Cmd/Ctrl + Y | Redo last action entered into cell's editor 
Cmd/Ctrl + Shift + Z | Redo last action entered into cell's editor 

### How has this been tested?

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes #9367

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2022-04-15 13:46 UTC, kirszenbaum approved these changes
I'll document these changes in #9271

2022-04-19 11:11 UTC, wszymanski requested changes
It seems that height of the editor isn't changed after undo action. It's updated just after pressing some extra key.

https://user-images.githubusercontent.com/141330/163991004-55b0b9e0-c016-41d5-ae46-45f47eacad90.mp4

edit: It works similarly for redo action.

2022-04-19 12:09 UTC, wszymanski approved these changes

2022-04-19 12:09 UTC, wszymanski commented on handsontable/src/editors/textEditor/__tests__/caretPositioner.unit.js
> +        updateCaretPosition('endd', textarea);
```suggestion
        updateCaretPosition('unknown', textarea);
```

2022-04-19 12:09 UTC, wszymanski commented on handsontable/src/editors/textEditor/__tests__/caretPositioner.unit.js
> +        updateCaretPosition('endd', textarea);
```suggestion
        updateCaretPosition('unknown', textarea);
```

2022-04-20 06:52 UTC, budnix commented
> It seems that height of the editor isn't changed after undo action. It's updated just after pressing some extra key.

I fixed that within https://github.com/handsontable/handsontable/pull/9393/commits/c07a39e2396f00fc05efe247b5c9449139ccfa9c.

2022-04-20 11:36 UTC, wszymanski approved these changes

2022-04-20 14:37 UTC, merged