Remove hardcoded "htLeft" alignment from demos
handsontable/handsontable pull request #9420
Opened 2022-04-25 11:41 UTC by budnix

### Context

The PR updates all demos (from the examples package) to add support for different settings for the layout direction option. From now on, all demos should look just as good as with left-to-right direction and right-to-left.

The PR shows that there is a need to expose a private API to the public. The methods `isRtl`, `isLtr`, and `getDirectionFactor` in the context of demos (and probably in the context of the user's apps) turned out to be very useful.

### How has this been tested?

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes #9419

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2022-04-25 13:21 UTC, wszymanski submitted a review, later dismissed

2022-04-26 11:58 UTC, warpech commented
This PR is required for the 12.0.0 release, but it does not need to be merged to the release branch, because the examples are deployed from the `develop` branch.

2022-04-26 12:01 UTC, budnix commented
> This PR is required for the 12.0.0 release, but it does not need to be merged to the release branch, because the examples are deployed from the `develop` branch.

I think that PR is required to be merged to the release branch as it contains new methods that from now on are part of the public API. The docs need to be regenerated after merge as well.

2022-04-27 10:22 UTC, kirszenbaum requested changes

2022-04-27 10:22 UTC, kirszenbaum commented on .changelogs/9419.json
> +  "title": "Expose `isRtl`, `isLtr`, and `getDirectionFactor` methods to the public API.",
```suggestion
  "title": "Exposed the `isRtl()`, `isLtr()`, and `getDirectionFactor()` methods to the public API.",
```

2022-04-27 10:22 UTC, kirszenbaum commented on handsontable/src/core.js
> +   * Checks if the table is rendered using right-to-left layout direction.
```suggestion
   * Checks if the grid is rendered using the right-to-left layout direction.
```

2022-04-27 10:22 UTC, kirszenbaum commented on handsontable/src/core.js
> +   * Checks if the table is rendered using left-to-right layout direction.
```suggestion
   * Checks if the grid is rendered using the left-to-right layout direction.
```

2022-04-27 10:30 UTC, wszymanski approved these changes

2022-04-27 10:31 UTC, kirszenbaum approved these changes

2022-04-27 10:32 UTC, merged