Add serbian language
handsontable/handsontable pull request #9469
Opened 2022-05-09 14:51 UTC by ivkeapp

### Context
Let's all contribute

### Types of changes

- [ ] Added Serbian language

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2022-05-10 07:25 UTC, Cookie994 approved these changes
Translation looking good! ^^

2022-05-10 07:25 UTC, AMBudnik commented
Hi @ivkeapp 

Thank you for sharing the translation! Could you also sign [our CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1) and change the branch to `develop`?

2022-05-10 07:28 UTC, ivkeapp commented
> Hi @ivkeapp
> 
> Thank you for sharing the translation! Could you also sign [our CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1) and change the branch to `develop`?

Hello, gladly. :)

2022-05-10 07:40 UTC, ivkeapp commented
> Translation looking good! ^^

Thanks

2022-05-10 07:44 UTC, nemanjadvlp approved these changes
Good translation

2022-05-10 07:48 UTC, AMBudnik commented
Thank you! I will pass the pull request for the code review.

2022-05-10 07:55 UTC, ivkeapp commented
> Thank you! I will pass the pull request for the code review.

Thank you 👍

2022-05-10 08:38 UTC, ivkeapp commented on .changelogs/9419.json
>  {
Sure.

2022-05-10 08:40 UTC, ivkeapp commented on .changelogs/9419.json
>  {
Hope I did it right @budnix

2022-05-10 09:19 UTC, budnix requested changes
Thanks! We are almost there. Just some nitpick changes to be done.
 * Revert `.changelogs/9419.json` changelog file as it belongs to another PR (you've already added correct one - 9469.json);
 * Our linter requires new lines at the end of each source code file. Can you add that?
   * https://github.com/handsontable/handsontable/pull/9469/files#diff-cbe5e6112b4f48d06305fb52e3d6a41c30f28cd25c11761fc6d3d49e240f953dR7
   * https://github.com/handsontable/handsontable/pull/9469/files#diff-c3872efa05482bf7db8e0a315d98d7c8dd95b2eb869c8d9d49b6dfe4ce5bb707R102

2022-05-10 10:40 UTC, merged

2022-05-10 10:40 UTC, budnix commented
@ivkeapp Thanks!

2022-05-10 10:42 UTC, budnix commented
@kirszenbaum May I ask you to prepare the PR with docs changes about the new language?

2022-06-28 11:21 UTC, AMBudnik commented
Hi @ivkeapp I'm more than happy to announce that we just released Handsontable v12.1.0 with the Serbian translation. Thanks again for the contribution!

2022-11-18 12:41 UTC, adrianszymanski89 commented
Hi @ivkeapp. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

2022-11-18 15:37 UTC, ivkeapp commented
Hi, I have done a translation to Serbian :)
    On Friday, November 18, 2022 at 01:41:18 PM GMT+1, adrianszymanski89 ***@***.***> wrote:  
 
 


Hi @ivkeapp. We just announced an introduction of a new functionality called Copy with headers. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: #10112

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>