Docs: Adding 12.0.1 docs
handsontable/handsontable pull request #9485
Opened 2022-05-12 18:00 UTC by kirszenbaum

This PR:
- Edits the 12.0.1 changelog entries
- Adds the 12.0.1 release notes

2022-05-12 18:20 UTC, budnix approved these changes

2022-05-13 08:20 UTC, warpech requested changes

2022-05-13 08:28 UTC, kirszenbaum commented on CHANGELOG.md
> +- Fixed an issue where (un)checking a checkbox changed the cell width. [#8211](https://github.com/handsontable/handsontable/issues/8211)
Ok, updated: [d15c71c](https://github.com/handsontable/handsontable/pull/9485/commits/d15c71c2b8062acc5be81b6c31bae1a726a1547f)

2022-05-13 08:28 UTC, kirszenbaum commented on CHANGELOG.md
> +- Fixed an issue where setting the `autoRowSize` option to `true` and (un)checking a checkbox in a row with multi-line cell values caused rows to align incorrectly. [#7102](https://github.com/handson
Ok, updated: [d15c71c](https://github.com/handsontable/handsontable/pull/9485/commits/d15c71c2b8062acc5be81b6c31bae1a726a1547f)

2022-05-13 08:31 UTC, merged