Removed inconsistency in the `ShortcutManager`
handsontable/handsontable pull request #9568
Opened 2022-06-07 16:17 UTC by wszymanski

### Context

At first, I thought that it may be Gecko bug. However, after some research I've found that it seems to be a desired change that `keydown` and `keyup` events are thrown (even when there is no key pressed) for browser's autofill action. There was a bugfix which [introduced that in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=581537).

After further investigation I've found that we have some inconsistency. Events outside the table shouldn't be handled (there is performed event on `input` outside the table). While the `mousedown` event wasn't handled, both `keyup` or `blur` has been.

This PR fixed inconsistency in the `ShortcutManager`. After that change it would be not needed to do anything more. Hover, I'm introducing also change for checking whether an `event` has `key` defined.

### How has this been tested?

Checked 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9562 

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

2022-06-09 06:27 UTC, budnix requested changes

2022-06-09 06:27 UTC, budnix commented on handsontable/src/shortcuts/recorder.js
> +
This line causes a bug where the Control/Command key is not released when the browser window is blurred. Thus, after the window is focused again the non-contiguous selection is locked even when the meta key is not pressed at all. 

![Kapture 2022-06-09 at 08 24 19](https://user-images.githubusercontent.com/571316/172779251-e7c1769d-6e91-4a75-a2e5-05585e14a96e.gif)

2022-06-10 12:45 UTC, budnix approved these changes
👍

2022-06-10 12:48 UTC, wszymanski commented
@warpech @aninde Should it be merged? Will it be released for `12.1.0`?

2022-06-10 12:52 UTC, budnix commented
> @warpech @aninde Should it be merged? Will it be released for `12.1.0`?

The issue is marked to be released in 12.1.0 in [the ZenDesk](https://app.zenhub.com/workspaces/handsontable-development-619c0f46f1c2d20014fc4595/issues/handsontable/handsontable/9562). Definitely you should merge it :)

2022-06-10 13:03 UTC, wszymanski commented
> > @warpech @aninde Should it be merged? Will it be released for `12.1.0`?
> 
> The issue is marked to be released in 12.1.0 in [the ZenHub](https://app.zenhub.com/workspaces/handsontable-development-619c0f46f1c2d20014fc4595/issues/handsontable/handsontable/9562). Definitely you should merge it :)

Indeed, thanks.

2022-06-10 13:08 UTC, merged