Docs: Improve Docs on mobile devices
handsontable/handsontable pull request #9926
Opened 2022-09-20 07:26 UTC by budnix

### Context

The PR improves the UI styling, content styling, and demos for mobile devices (narrow viewports). The PRs changes:
 * TBD

### How has this been tested?

I tested the changes using the Chrome Toggle device toolbar.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. fixes #9831

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2022-09-20 11:55 UTC, wszymanski requested changes
Looks good, just one problem found. I can't see the searchbar. Please verify the issue.

<img width="1275" alt="Screenshot 2022-09-20 at 13 44 01" src="https://user-images.githubusercontent.com/141330/191250441-f4d5841d-a2ce-47ec-953a-30a1e8e2951e.png">

<img height="500" alt="Screenshot 2022-09-20 at 13 44 01" src="https://user-images.githubusercontent.com/141330/191250930-4a242e73-ec07-4c56-9d9a-7b1db13a370d.jpg">

<img height="500" alt="Screenshot 2022-09-20 at 13 44 01" src="https://user-images.githubusercontent.com/141330/191250934-a94f4665-63ca-4be3-8b55-90c89634ab4a.jpg">

Device: OnePlus Nord 2 5G, Android 11

2022-09-20 11:55 UTC, wszymanski commented on docs/.vuepress/theme/styles/index.styl
> +  }
Just a minor styling change.

```suggestion
  td {
    white-space: normal;

    @media (max-width: $MQNarrow) {
      white-space: nowrap;
    }
  }
```

2022-09-20 13:02 UTC, budnix commented
> Looks good, just one problem found. I can't see the searchbar. Please verify the issue.

The issue only happens when you run Docs locally on a different port than `8080`. The issue is not related to this task.

2022-09-20 13:03 UTC, budnix commented on docs/.vuepress/theme/styles/index.styl
> +  }
Fixed within https://github.com/handsontable/handsontable/pull/9926/commits/618545d12ff033e16dbcd0fad961da0a90b1ca07

2022-09-20 15:03 UTC, wszymanski requested changes
As wrote here (`I've found yet another problem related to searchbar when dark mode is enabled. A text is overlapping the bar`): https://github.com/handsontable/handsontable/pull/9926#issuecomment-1252388859

2022-09-21 06:31 UTC, budnix commented
> As wrote here (`I've found yet another problem related to searchbar when dark mode is enabled. A text is overlapping the bar`): [#9926 (comment)](https://github.com/handsontable/handsontable/pull/9926#issuecomment-1252388859)

Thanks for spotting that. I've fixed the issue. Can you check now?

2022-09-21 11:11 UTC, wszymanski approved these changes

2022-09-21 11:16 UTC, merged