replace useRef() in the snippets and examples with useRef(null)
handsontable/handsontable pull request #9936
Opened 2022-09-21 13:09 UTC by maciejbo-handsontable

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [x ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

[skip changelog]

2022-09-22 10:52 UTC, budnix requested changes
I think that you missed the example at https://github.com/handsontable/handsontable/blame/docs/issue-9909-1/docs/content/guides/cell-features/clipboard.md#L176. Can you update that one too?

2022-09-23 09:18 UTC, wszymanski requested changes
Thanks for your effort. However, there are still some snippets where `useRef()` occurs.

<img width="767" alt="Screenshot 2022-09-23 at 11 18 12" src="https://user-images.githubusercontent.com/141330/191929758-1453ca99-6779-4cbe-8a14-2518bc85d175.png">

Please also provide a short description.

2022-09-23 10:32 UTC, maciejbo-handsontable commented
> I think that you missed the example at https://github.com/handsontable/handsontable/blame/docs/issue-9909-1/docs/content/guides/cell-features/clipboard.md#L176. Can you update that one too?

sure, should be available already.

> Thanks for your effort. However, there are still some snippets where useRef() occurs.

hey, yes - wasn't sure if these changes should be implemented out of the `docs` folder in current task. Now everything should be fine, please check.

2022-09-23 10:44 UTC, wszymanski approved these changes

2022-09-23 10:55 UTC, budnix approved these changes

2022-09-23 13:54 UTC, merged