Implement ability to add row and/or column in the specified position
handsontable/handsontable pull request #9955
Opened 2022-09-27 09:03 UTC by budnix

### Context

The PR extends the Core `alter` method for the ability to add rows or columns in the specified position based on the given index.

#### Insert rows
##### Before
There is only one alter action `insert_row` that allows inserting rows only above. For example `hot.alter('insert_row', 1)`.

##### After
The `insert_row` action is for backward compatibility and still works as previously, but additionally, the PR adds two new ones.
 *  `insert_row_above` Works the same as `insert_row`, but the name is more explicit.
 *  `insert_row_below` The new alter action that allows adding new rows below.

#### Insert columns
##### Before
There is only one alter action `insert_col` that allows inserting columns only on the left (or right in RTL). For example `hot.alter('insert_col', 1)`.

##### After
The `insert_col` action is for backward compatibility and still works as previously, but additionally, the PR adds two new ones.
 *  `insert_col_start` Works the same as `insert_col`, but the name is more explicit.
 *  `insert_col_end` The new alter action that allows adding new columns on the right (or on the left in RTL).

### How has this been tested?

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes #9471

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

2022-10-11 11:01 UTC, wszymanski requested changes
Thanks for fixing bugs. It works as desired. I've found just one bug. The warning is called also for calling `insert_row_below`, `insert_row_above`, `insert_col_end` and `insert_col_start`.

2022-10-11 11:13 UTC, budnix commented on handsontable/src/core.js
> +          }
Fixed within https://github.com/handsontable/handsontable/pull/9955/commits/1964a4f1547b4a827e8a9611952565771121791f

2022-10-11 11:13 UTC, budnix commented on handsontable/src/core.js
> +          }
Fixed within https://github.com/handsontable/handsontable/pull/9955/commits/1964a4f1547b4a827e8a9611952565771121791f

2022-10-11 11:22 UTC, wszymanski approved these changes

2022-10-12 14:53 UTC, kirszenbaum requested changes

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/core.js
> +              // TODO: The logic here should be handled by selection module.
```suggestion
              // Moving the selection (if it exists) downward – it should be applied to the "old" row.
              // TODO: The logic here should be handled by selection module.
```

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/core.js
> +          // action the column is added on the left of the dataset.
```suggestion
          // The line below ensures backward compatibility of the `alter()` method's `insert_col` action.
          // Calling the `insert_col` action with no arguments adds a new column to the right of the data set.
          // Calling the `insert_col_start` action adds a new column to the left of the data set.
```

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/core.js
> +              // Moving right the selection (when it exist). It should be present on the "old" row.
```suggestion
              // Moving the selection (if it exists) rightward – it should be applied to the "old" column.
```

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/core.js
> +   *    <li> `'insert_col_end'` (inserts column at the right in LTR and at the left in RTL [layout direction](@/guides/internationalization/layout-direction.md) mode) </li>
```suggestion
   *    <li> `'insert_row'` (<b>deprecated</b>, an alias for `'insert_row_above'`) </li>
   *    <li> `'insert_row_above'` </li>
   *    <li> `'insert_row_below'` </li>
   *    <li> `'insert_col'` (<b>deprecated</b>, an alias for `'insert_col_start'`) </li>
   *    <li> `'insert_col_start'` (depending on the [`layoutDirection`](@/api/options.md#layoutdirection), inserts a column to the left (in LTR) or to the right (in RTL) </li>
   *    <li> `'insert_col_end'` (depending on the [`layoutDirection`](@/api/options.md#layoutdirection), inserts a column to the right (in LTR) or to the left (in RTL) </li>
```

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/core.js
> +   * // Insert new row below the row at given visual index.
```suggestion
   * // below the row with the given visual index, insert a new row
```

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/dataMap/dataMap.js
> +   * @param {'above'|'below'} [options.mode] Sets where the row will be inserted. Above or below the passed index.
```suggestion
   * @param {'above'|'below'} [options.mode] Sets where the row is inserted: above or below the passed index.
```

2022-10-12 14:53 UTC, kirszenbaum commented on handsontable/src/dataMap/dataMap.js
> +   * @param {'start'|'end'} [options.mode] Sets where the column will be inserted. Start (left in LTR) or end (right in LTR)
```suggestion
   * @param {'start'|'end'} [options.mode] Sets where the column is inserted: at the start (left in [LTR](@/api/options.md#layoutdirection), right in [RTL](@/api/options.md#layoutdirection)) or at the end (right in LTR, left in LTR)
```

2022-10-12 14:53 UTC, kirszenbaum commented on .changelogs/9471.json
> +  "title": "Added a feature that allows adding row and column in the specified position. Above or Below the given index.",
```suggestion
  "title": "Added a new feature that lets you add rows and columns in a specified position (above or below the given index).",
```

2022-10-12 14:57 UTC, wszymanski submitted a review, later dismissed

2022-10-12 15:53 UTC, kirszenbaum approved these changes

2022-10-13 06:53 UTC, merged

2022-10-18 14:35 UTC, aninde commented
@budnix I really like the huge amount of tests added and also include `layoutDirection: 'rtl'`, but I don't see any tests written for `manualColumnFreeze` or `fixedColumnsStart`. Should this feature not be supplemented by such?